" Generated by hive-addon for runtime hive-carto-flow. Removed when the addon shuts down.
if exists('g:loaded_hive_runtime_hive_carto_flow')
  finish
endif
let g:loaded_hive_runtime_hive_carto_flow = 1

function! s:activate() abort
  let g:carto_flow_port_file = '/home/leibniz/.local/state/hive/carto-flow/vim.port'
  let g:carto_flow_auto_open = 1
  CartoFlowConnect
endfunction

if v:vim_did_enter
  call s:activate()
else
  augroup hive_runtime_hive_carto_flow
    autocmd!
    autocmd VimEnter * ++once call s:activate()
  augroup END
endif
