// GNU User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1687043547);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1687109563);
user_pref("app.update.lastUpdateTime.region-update-timer", 1687043787);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1687043307);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1687043427);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1687043216);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1687043667);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{425ba2e3-02b4-4b8b-aa88-83da65e977d8}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20230606000000");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage", "https://check.torproject.org/");
user_pref("browser.startup.lastColdStartupCheck", 1687109533);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"gnuzilla-ext-workarounds_gnu_org-browser-action\",\"jid1-ktlzuoiikvffew_jetpack-browser-action\",\"jsr_javascriptrestrictor-browser-action\",\"tprb_addon_searxes_danwin1210_me-browser-action\",\"https-everywhere_eff_org-browser-action\",\"_b7f9d2cd-d772-4302-8c3f-eb941af36f76_-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"gnuzilla-ext-workarounds_gnu_org-browser-action\",\"jid1-ktlzuoiikvffew_jetpack-browser-action\",\"jsr_javascriptrestrictor-browser-action\",\"tprb_addon_searxes_danwin1210_me-browser-action\",\"https-everywhere_eff_org-browser-action\",\"_b7f9d2cd-d772-4302-8c3f-eb941af36f76_-browser-action\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("distribution.iniFile.exists.appversion", "102.12.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1687109540);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230606000000");
user_pref("extensions.lastAppVersion", "102.12.0");
user_pref("extensions.lastPlatformVersion", "102.12.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.https-everywhere@eff.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-KtlZuoiikVfFew@jetpack", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jsr@javascriptrestrictor", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.tprb.addon@searxes.danwin1210.me", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{b7f9d2cd-d772-4302-8c3f-eb941af36f76}", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"23e26c21-7713-40d5-b9c8-1e6cc734b351\",\"formautofill@mozilla.org\":\"c3bc9dfe-47ea-480a-8082-8bde5c8920f9\",\"pictureinpicture@mozilla.org\":\"7d12d519-180f-412e-833f-ed0ab98c376e\",\"screenshots@mozilla.org\":\"bb879f8d-cba8-4790-b66f-71d8c4aab5d9\",\"webcompat-reporter@mozilla.org\":\"d18ba4d5-df9c-4bb2-84d3-d303ca4847cc\",\"webcompat@mozilla.org\":\"2890ae41-78cf-4bc6-8be5-3f8466a538f3\",\"libgen.merepack@librifyjs\":\"fcc08003-d6a9-4e95-b294-82d5fc21a8cd\",\"https-everywhere@eff.org\":\"b5145135-89bd-4e30-9e55-570074c66991\",\"jsr@javascriptrestrictor\":\"3f1dc387-d4d3-4037-9a74-55f472b173ec\",\"SubmitMe@0xbeef.coffee\":\"f0c8e72a-d092-4f79-bba0-dc0bc4ed5bcb\",\"tprb.addon@searxes.danwin1210.me\":\"2a56153a-16c5-46de-8f0e-d7dc10d6b39e\",\"{b7f9d2cd-d772-4302-8c3f-eb941af36f76}\":\"e7d68a8b-e426-46df-b58e-c5d5f0df3b23\",\"FreeUSPS@0xbeef.coffee\":\"4edd07e5-46d7-4b8f-893a-65f2417c898c\",\"jid1-KtlZuoiikVfFew@jetpack\":\"5f70d6ca-a4d9-4547-bd72-4e2fa73a4056\",\"gnuzilla-ext-workarounds@gnu.org\":\"19731f87-0562-4bb6-ac00-441468ff5020\",\"default-theme@mozilla.org\":\"32ebf3a3-533c-424f-944a-22c3dbbe092e\",\"addons-search-detection@mozilla.com\":\"9eb8ada0-4360-44a8-a922-345573df423a\",\"ddg@search.mozilla.org\":\"31d202df-0adc-499b-9325-cf0d867b0a73\",\"wikipedia@search.mozilla.org\":\"3ddd9cb3-8b0b-43bd-9cfb-ad24055c2b26\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1687043129);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1687044178);
user_pref("media.gmp-manager.buildID", "20230606000000");
user_pref("media.gmp-manager.lastCheck", 1687044019);
user_pref("media.gmp-manager.lastEmptyCheck", 1687044019);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.proxy.socks", "localhost");
user_pref("network.proxy.socks_port", 9050);
user_pref("network.proxy.type", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1687044178);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1687044178706");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "70537c7a-b1b7-45fb-992d-cc119bb2fa8c");
user_pref("services.sync.engine.addresses.available", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1687044178);
user_pref("toolkit.startup.last_success", 1687109532);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20230606000000");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
