#!/bin/bash

set -e # stop script, in case of error 

TMP="$DOTFILES/tmp"
mkdir -p "$TMP"

cd "$TMP"

URL=$(wget -qO- https://www.anaconda.com/download/success | grep -oP 'https://repo\.anaconda\.com/archive/Anaconda3-[^"]*-Linux-x86_64\.sh' | head -n1)

if [[ -z "$URL" ]]; then
  echo "❌ Não foi possível encontrar a URL do instalador."
  exit 1
fi

echo "✅ Baixando Anaconda de: $URL"
wget -O anaconda.sh "$URL"

bash anaconda.sh -b -p "$HOME/anaconda3"

eval "$($HOME/anaconda3/bin/conda shell.bash hook)"
conda init
conda create -n default -y

rm -rf "$TMP"

conda activate default
