#!/bin/bash

sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386

cd $DOTFILES/gitthings/

wget https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2023.2.1.24/android-studio-2023.2.1.24-linux.tar.gz

cd android-studio/bin/
bash studio.sh

sudo apt install google-android-emulator-installer
# sudo apt-get install android-studio
