#!/usr/bin/bash

sudo apt-get install unzip
asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
asdf plugin-add erlang
asdf plugin-add elixir
asdf plugin-add nodejs

echo "==> Install ASDF plugin dependencies"

echo "===> Installing ASDF common plugin deps"
sudo apt-get -qq install automake autoconf libreadline-dev libncurses-dev libssl-dev \
    libyaml-dev libxslt-dev libffi-dev libtool unixodbc-dev

echo "===> Installing ASDF Erlang plugin deps"
sudo apt-get -qq install build-essential libncurses5-dev libwxgtk3.2-dev libgl1-mesa-dev \
    libglu1-mesa-dev libpng-dev libssh-dev unixodbc-dev xsltproc fop

echo "===> Installing ASDF Node.js plugin deps"
sudo apt-get -qq install dirmngr gpg

asdf install latest
asdf global elixir latest
asdf global erlang latest
asdf global nodejs latest
