#!/usr/bin/bash

cd $DOTFILES
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
sudo dpkg -i cuda-keyring_1.1-1_all.deb
sudo apt-get update
sudo apt-get -y install cuda-toolkit-13-1
sudo apt-get install -y cuda-drivers
sudo apt-get install -y cudnn9-cuda-13
sudo apt-get -y install cudnn9-jit-cuda-13
#sudo apt-get install -y nvidia-driver-570-open
#sudo apt-get install -y cuda-drivers-fabricmanager-570
