#!/bin/sh
sudo apt-get install -y uidmap systemd-container dbus-user-session
sudo apt-get install docker-ce-rootless-extras

filename=$(echo $HOME/bin/rootlesskit | sed -e s@^/@@ -e s@/@.@g)
cat <<EOF > ~/${filename}
abi <abi/4.0>,
include <tunables/global>

"$HOME/bin/rootlesskit" flags=(unconfined) {
  userns,

  include if exists <local/${filename}>
}
EOF
sudo mv ~/${filename} /etc/apparmor.d/${filename}

systemctl restart apparmor.service

cd $DOTFILES/gitthings
curl -fsSL https://get.docker.com/rootless -o rootless.sh
chmod +x rootless.sh
systemctl --user stop docker
rm -f $HOME/bin/dockerd
sudo systemctl disable --now docker.service docker.socket
sudo rm /var/run/docker.sock
$HOME/bin/dockerd-rootless-setuptool.sh uninstall -f ; $HOME/bin/rootlesskit rm -rf "$HOME/.local/share/docker"

bash ./rootless.sh
