#!/usr/bin/bash

sudo apt-get update
sudo apt-get install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

## Start docker service
sudo service docker start

# Set up temporary directory
TMP="$HOME/tmp"
mkdir -p $TMP

# Change to the temporary directory
cd $TMP

# Download the Docker Desktop deb package URL
DEB_URL=$(wget -O - https://docs.docker.com/desktop/install/ubuntu/ 2>/dev/null | \
    sed -ne 's@.*\(https:\/\/desktop\.docker\.com\/linux\/main\/amd64\/docker-desktop-amd64\.deb\?.*\)".*DEB package.*@\1@p')

if [ -z "$DEB_URL" ]; then
  echo "Failed to find the Docker Desktop deb package URL."
  exit 1
fi

# Download the Docker Desktop deb package
wget -O docker-desktop-amd64.deb "$DEB_URL"
if [ $? -ne 0 ]; then
  echo "Failed to download the Docker Desktop deb package."
  exit 1
fi

# Ensure the downloaded file has the correct permissions
chmod 644 docker-desktop-amd64.deb

# Check if the downloaded file is a valid deb package
if ! dpkg --info docker-desktop-amd64.deb &>/dev/null; then
  echo "The downloaded file is not a valid deb package."
  rm -f docker-desktop-amd64.deb
  exit 1
fi

# Install the Docker Desktop deb package
sudo apt-get update
sudo apt-get install -y ./docker-desktop-amd64.deb
if [ $? -ne 0 ]; then
  echo "Failed to install the Docker Desktop deb package."
  rm -f docker-desktop-amd64.deb
  exit 1
fi

# Clean up
rm -rf $TMP

# Notify the user
echo "Docker Desktop installation is complete."

systemctl --user enable docker-desktop
systemctl --user start docker-desktop
