#!/usr/bin/bash

rm -rf $HOME/.emacs.d
git clone --depth 1 https://github.com/doomemacs/doomemacs $HOME/.emacs.d
$HOME/.emacs.d/bin/doom install

rm -rf $HOME/.doom.d
ln -sf $HOME/dotfiles/.doom.d $HOME

echo "This config needs copilot language serve... So, we are going to install it: \n"
sudo npm i -g @github/copilot-language-server
