#!/usr/bin/bash

## Where we can install "git things"
cd $DOTFILES/gitthings

## Build from source
git clone https://github.com/elkowar/eww
cd eww

## Dependencies
sudo apt-get update
sudo apt-get install libgtk-layer-shell-dev libdbusmenu-gtk3-dev libdbusmenu-glib-dev gir1.2-dbusmenu-glib-0.4 

## Make it available for build
export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH

## Build it
cargo build --release --no-default-features --features x11
