#!/usr/bin/bash

GO_FILE=$(wget -O - https://go.dev/dl/ 2>/dev/null | sed -ne 's@.*\(\/go1\.[0-9]*\.[0-9]*\.linux-amd64\.tar\.gz\).*@\1@p'  2>&1 | head -n 1| tr -d /)
URL_DOWNLOAD="https://go.dev/dl/$GO_FILE"

echo "URL_DOWNLOAD=$URL_DOWNLOAD"
wget "$URL_DOWNLOAD"

sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf $GO_FILE

echo "Deleating $GO_FILE (Cleaning)"
rm $GO_FILE

echo 'export PATH=$PATH:/usr/local/go/bin'
export PATH=$PATH:/usr/local/go/bin

go install github.com/x-motemen/gore/cmd/gore@latest
go install github.com/stamblerre/gocode@latest
go install golang.org/x/tools/cmd/godoc@latest
go install golang.org/x/tools/cmd/goimports@latest
go install golang.org/x/tools/cmd/gorename@latest
go install github.com/cweill/gotests/gotests@latest
go install github.com/fatih/gomodifytags@latest

