#!/bin/bash

# Proto buffer for go (gRPC)
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

# Go repl
go install github.com/x-motemen/gore/cmd/gore@latest

# Swaggo (tool to jack-in swagger docs into your application)
go install github.com/swaggo/swag/cmd/swag@latest


