#!/usr/bin/bash

#curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | apt-key add -
#echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/migrate.list
#apt-get update
#apt-get install -y migrate

go install github.com/golang-migrate/migrate/cmd/migrate@latest
cd $GOPATH/src/github.com/golang-migrate/migrate/cmd/migrate
git checkout $TAG  # e.g. v4.1.0
# Go 1.16+
go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@$TAG
