#!/usr/bin/bash

go install sigs.k8s.io/kind@latest

#[ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.29.0/kind-linux-amd64
#chmod +x ./kind
#sudo mv ./kind /usr/local/bin/kind
