#!/usr/bin/bash

sudo apt update

sudo apt install -y \
    autotools-dev autoconf autopoint libtool gettext \
    libgtk-3-dev libgdk-pixbuf2.0-dev \
    mplayer ffmpeg imagemagick sox perl \
    libpng-dev libx11-dev libxrender-dev \
    libpulse-dev libjack-jackd2-dev \
    libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libswresample-dev \
    libfftw3-dev libunicap2-dev \
    liborc-0.4-dev libopencv-dev frei0r-plugins-dev ladspa-sdk \
    libsdl2-dev libprojectm-dev projectm-data \
    libtheora-dev libvorbis-dev libdv4-dev libbz2-dev \
    libavc1394-dev libraw1394-dev libogg-dev \
    libgl-dev libglew-dev

sudo apt install -y \
    python3 mkvtoolnix vorbis-tools libmatroska-dev ogmtools \
    dvgrab frei0r-plugins icedax lame \
    libvisual-0.4-dev libsdl1.2-dev \
    libtheora-bin libvorbis-dev mjpegtools \
    libpulse0 libasound2-dev

sudo apt install yt-dlp

sudo apt install gstreamer1.0-plugins-bad
sudo apt install -y \
    libopencv-dev frei0r-plugins-dev libvisual-0.4-dev \
    libsdl1.2-dev libprojectm-dev projectm-data \
    libmatroska-dev gpac mencoder


