#!/bin/bash

cd $DOTFILES/gitthings/
git clone https://github.com/yshui/picom.git

cd picom
git submodule update --init --recursive
meson setup --buildtype=release . build
ninja -C build
ninja -C build install
