#!/usr/bin/bash

#sudo apt update
#sudo apt-get install sbcl

cd $DOTFILE/gitthings
git clone git://git.code.sf.net/p/sbcl/sbcl
cd sbcl
sh make.sh

#curl -O https://beta.quicklisp.org/quicklisp.lisp
#curl -O https://beta.quicklisp.org/quicklisp.lisp.asc
#gpg --verify quicklisp.lisp.asc quicklisp.lisp
#sbcl --load quicklisp.lisp
#(quicklisp-quickstart:install)
sudo curl -o /tmp/ql.lisp http://beta.quicklisp.org/quicklisp.lisp
sbcl --no-sysinit --no-userinit --load /tmp/ql.lisp \
       --eval '(quicklisp-quickstart:install :path "~/.quicklisp")' \
       --eval '(ql:add-to-init-file)' \
#			 --eval '(ql:system-apropos "agnostic-lizard")'\
			 --eval '(ql:quickload :agnostic-lizard)' \
       --quit
