#!/bin/bash

# curl -L https://github.com/storj/storj/releases/latest/download/uplink_linux_amd64.zip -o uplink_linux_amd64.zip
# unzip -o uplink_linux_amd64.zip
# sudo install uplink /usr/local/bin/uplink

go get storj.io/uplink
