#!/usr/bin/bash

if [ -z "$DOTFILES" ]; then
  TMP=$(mktemp -d)
  DELETE_TMP=true
else
  TMP="$DOTFILES/gitthings/"
  DELETE_TMP=false
fi

mkdir -p $TMP
cd $TMP

sudo apt-get install xorg-dev build-essential libx11-dev x11proto-xext-dev libxrender-dev libxext-dev
git clone https://github.com/mmhobi7/xwinwrap.git
cd xwinwrap
make
sudo make install
make clean

if $DELETE_TMP; then
  rm -rf $TMP
fi
