#!/usr/bin/bash

TMP="$DOTFILES/tmp"
mkdir $TMP
cd $TMP

sudo apt-get install xorg-dev build-essential libx11-dev x11proto-xext-dev libxrender-dev libxext-dev
git clone https://github.com/mmhobi7/xwinwrap.git
cd xwinwrap
make
sudo make install
make clean

rm -rf $TMP
