(("default" . ((user-emacs-directory . "~/.emacs.d")))
 ("spacemacs" . ((user-emacs-directory . "~/spacemacs")))
 ("progress" . ((user-emacs-directory . "~/.ep")))
 ("doom" . ((user-emacs-directory . "~/doom-emacs")
            (env . ("DOOMDIR" . "~/doom-config"))))
 ("tecosaur" . ((user-emacs-directory . "~/.tecosaur.d"))))
