(("default" . ((user-emacs-directory . "~/.emacs.d")))
 ("spacemacs" . ((user-emacs-directory . "~/spacemacs")))
 ("progress" . ((user-emacs-directory . "~/.ep")))
 ("doom" . ((user-emacs-directory . "~/.edoom")))
 ("tecosaur" . ((user-emacs-directory . "~/.tecosaur.d"))))
