#!/bin/bash

if [[ -z "$(which vim)" || -z "$(which vimtutor)" ]]; then
  echo "Warning, doesn't look like you have full Vim version."
fi

ln -sf "$PWD/vimrc" "$HOME/.vimrc"
ln -sf "$PWD/.vim" "$HOME/.vim"
mkdir -p "$HOME/.vim/autoload"
ln -sf "$PWD/plug.vim" "$HOME/.vim/autoload/plug.vim"
