#!/bin/bash

sh "$HOME/.screenlayout/dual.sh" &
sleep 1

setbg "$HOME/Pictures/Wallpapers" &

dunst &

if [[ -n $(pgrep picom) ]]; then
  kill -9 $(pidof picom)
  picom --experimental-backends &
else
  picom --experimental-backends &
fi

if [[ -n $(pgreg xmonad) ]]; then
  exec xmonad
fi
