# btrfs-replace
# Autogenerated from man page /usr/share/man/man8/btrfs-replace.8.gz
complete -c btrfs-replace -s r -d 'only read from srcdev if no other zero-defect mirror exists'
complete -c btrfs-replace -s f -d 'force using and overwriting targetdev even if it looks like it contains a val…'
complete -c btrfs-replace -s B -d 'no background replace'
complete -c btrfs-replace -l enqueue -d 'wait if there\'s another exclusive operation running, otherwise continue'
complete -c btrfs-replace -s K -l nodiscard -d 'Do not perform whole device TRIM operation on devices that are capable of that'
complete -c btrfs-replace -s 1 -d 'print once instead of print continuously until the replace operation finishes…'

