# btrfs-receive
# Autogenerated from man page /usr/share/man/man8/btrfs-receive.8.gz
complete -c btrfs-receive -s f -d 'read the stream from FILE instead of stdin, . UNINDENT NDENT 0. 0'
complete -c btrfs-receive -s C -l chroot -d 'confine the process to path using chroot(1) . UNINDENT NDENT 0. 0'
complete -c btrfs-receive -s e -d 'terminate after receiving an end cmd marker in the stream'
complete -c btrfs-receive -s E -l max-errors -d 'terminate as soon as NERR errors occur while stream processing commands from …'
complete -c btrfs-receive -s m -d 'the root mount point of the destination filesystem '
complete -c btrfs-receive -l dump -d 'dump the stream metadata, one line per operation '
complete -c btrfs-receive -s q -l quiet -d '(deprecated) alias for global -q option . UNINDENT NDENT 0. 0'
complete -c btrfs-receive -s v -d '(deprecated) alias for global -v option . UNINDENT '
complete -c btrfs-receive -l verbose -d 'increase verbosity about performed actions, print details about each operation'

