# btrfs-check
# Autogenerated from man page /usr/share/man/man8/btrfs-check.8.gz
complete -c btrfs-check -s b -l backup -d 'use the first valid set of backup roots stored in the superblock'
complete -c btrfs-check -l check-data-csum -d 'verify checksums of data blocks'
complete -c btrfs-check -l chunk-root -d 'use the given offset bytenr for the chunk tree root'
complete -c btrfs-check -s E -l subvol-extents -d 'show extent state for the given subvolume'
complete -c btrfs-check -s p -l progress -d 'indicate progress at various checking phases'
complete -c btrfs-check -s Q -l qgroup-report -d 'verify qgroup accounting and compare against filesystem accounting'
complete -c btrfs-check -s r -l tree-root -d 'use the given offset \'bytenr\' for the tree root'
complete -c btrfs-check -l readonly -d '(default) run in read-only mode, this option exists to calm potential panic w…'
complete -c btrfs-check -s s -l super -d 'use Nth superblock copy, valid values are 0, 1 or 2 if the respective superbl…'
complete -c btrfs-check -l clear-space-cache -d 'completely wipe all free space cache of given type'
complete -c btrfs-check -l clear-ino-cache -d 'remove leftover items pertaining to the deprecated inode map feature'
complete -c btrfs-check -l repair -d 'enable the repair mode and attempt to fix problems where possible'
complete -c btrfs-check -l force -d 'warnings in documentation have shown to be insufficient'
complete -c btrfs-check -l init-csum-tree -d 'create a new checksum tree and recalculate checksums in all files'
complete -c btrfs-check -l init-extent-tree -d 'build the extent tree from scratch'
complete -c btrfs-check -l mode -d 'select mode of operation regarding memory and IO'

