# btrfs-quota
# Autogenerated from man page /usr/share/man/man8/btrfs-quota.8.gz
complete -c btrfs-quota -s s -d 'show status of a running rescan operation'
complete -c btrfs-quota -s w -d 'wait for rescan operation to finish(can be already in progress).  EXIT STATUS'

