# btrfs-rescue
# Autogenerated from man page /usr/share/man/man8/btrfs-rescue.8.gz
complete -c btrfs-rescue -s y -d 'assume an answer of yes to all questions'
complete -c btrfs-rescue -s h -d help
complete -c btrfs-rescue -s v -d '(deprecated) alias for global -v option NOTE: Since chunk-recover will scan t…'

