# btrfs-send
# Autogenerated from man page /usr/share/man/man8/btrfs-send.8.gz
complete -c btrfs-send -s e -d 'if sending multiple subvolumes at once, use the new format and omit the \\(aqe…'
complete -c btrfs-send -s p -d 'send an incremental stream from parent to subvol'
complete -c btrfs-send -s c -d 'use this snapshot as a clone source for an incremental send (multiple allowed)'
complete -c btrfs-send -s f -d 'output is normally written to standard output so it can be, for example, pipe…'
complete -c btrfs-send -l no-data -d 'send in NO_FILE_DATA mode '
complete -c btrfs-send -s q -l quiet -d '(deprecated) alias for global -q option'
complete -c btrfs-send -s v -l verbose -d '(deprecated) alias for global -v option . UNINDENT '

