# btrfs-balance
# Autogenerated from man page /usr/share/man/man8/btrfs-balance.8.gz
complete -c btrfs-balance -s s -s d -s m -d 'mean no filters'
complete -c btrfs-balance -s f -d 'force a reduction of metadata integrity, eg'
complete -c btrfs-balance -l background -l bg -d 'run the balance operation asynchronously in the background, uses fork(2) to s…'
complete -c btrfs-balance -l enqueue -d 'wait if there\'s another exclusive operation running, otherwise continue'
complete -c btrfs-balance -s v -d '(deprecated) alias for global \'-v\' option status [-v] <path> Show status of r…'

