# bundle-gem
# Autogenerated from man page /usr/share/man/man1/bundle-gem.1.gz
complete -c bundle-gem -l exe -s b -l bin -d 'Specify that Bundler should create a binary executable (as exe/GEM_NAME) in t…'
complete -c bundle-gem -l no-exe -d 'Do not create a binary (overrides --exe specified in the global config)'
complete -c bundle-gem -l coc -d 'Add a CODE_OF_CONDUCT. md file to the root of the generated project'
complete -c bundle-gem -l no-coc -d 'Do not create a CODE_OF_CONDUCT'
complete -c bundle-gem -l ext -d 'Add boilerplate for C extension code to the generated project'
complete -c bundle-gem -l no-ext -d 'Do not add C extension code (overrides --ext specified in the global config)'
complete -c bundle-gem -l mit -d 'Add an MIT license to a LICENSE'
complete -c bundle-gem -l no-mit -d 'Do not create a LICENSE. txt (overrides --mit specified in the global config)'
complete -c bundle-gem -s t -l test -l test -l test -d 'Specify the test framework that Bundler should use when generating the project'
complete -c bundle-gem -l ci -l ci -l ci -l ci -l ci -d 'Specify the continuous integration service that Bundler should use when gener…'
complete -c bundle-gem -l linter -l linter -l linter -d 'Specify the linter and code formatter that Bundler should add to the project\'…'

