# cifs.idmap
# Autogenerated from man page /usr/share/man/man8/cifs.idmap.8.gz
complete -c 'cifs.idmap' -l help -s h -d 'Print the usage message and exit'
complete -c 'cifs.idmap' -l timeout -s t -d 'Set the expiration timer, in seconds on the key'
complete -c 'cifs.idmap' -l version -s v -d 'Print version number and exit'

