# colorscript
# Autogenerated from man page /usr/local/man/man1/colorscript.1.gz
complete -c colorscript -s h -l help
complete -c colorscript -s l -l list
complete -c colorscript -s r -l random
complete -c colorscript -s e -l exec
complete -c colorscript -s b -l blacklist

