# corelist.1perl
# Autogenerated from man page /usr/share/man/man1/corelist.1perl.gz
complete -c 'corelist.1perl' -s a -d 'lists all versions of the given module (or the matching modules, in case you …'
complete -c 'corelist.1perl' -s d -d 'finds the first perl version where a module has been released by date, and no…'
complete -c 'corelist.1perl' -l diff -d 'Given two versions of perl, this prints a human-readable table of all module …'
complete -c 'corelist.1perl' -s '?' -o help -d 'help! help! help! to see more help, try --man'
complete -c 'corelist.1perl' -o man -d 'all of the help'
complete -c 'corelist.1perl' -s v -d 'lists all of the perl release versions we got the CoreList for'
complete -c 'corelist.1perl' -s r -d 'lists all of the perl releases and when they were released '
complete -c 'corelist.1perl' -l utils -d 'lists the first version of perl each named utility program was released with '
complete -c 'corelist.1perl' -l feature -s f -d 'lists the first version bundle of each named feature given'

