# cxl-disable-port
# Autogenerated from man page /usr/share/man/man1/cxl-disable-port.1.gz
complete -c cxl-disable-port -s e -l endpoint
complete -c cxl-disable-port -s f -l force
complete -c cxl-disable-port -l debug

