# cxl-set-partition
# Autogenerated from man page /usr/share/man/man1/cxl-set-partition.1.gz
complete -c cxl-set-partition -s S -l serial
complete -c cxl-set-partition -s t -l type
complete -c cxl-set-partition -s s -l size
complete -c cxl-set-partition -s a -l align
complete -c cxl-set-partition -s v

