# cxl-enable-port
# Autogenerated from man page /usr/share/man/man1/cxl-enable-port.1.gz
complete -c cxl-enable-port -s e -l endpoint
complete -c cxl-enable-port -s m -l enable-memdevs
complete -c cxl-enable-port -l debug

