# cxl-disable-memdev
# Autogenerated from man page /usr/share/man/man1/cxl-disable-memdev.1.gz
complete -c cxl-disable-memdev -s S -l serial
complete -c cxl-disable-memdev -s f -l force
complete -c cxl-disable-memdev -s v

