# debugfs.reiserfs
# Autogenerated from man page /usr/share/man/man8/debugfs.reiserfs.8.gz
complete -c 'debugfs.reiserfs' -s j -d 'prints the contents of the journal'
complete -c 'debugfs.reiserfs' -s J -d 'prints the journal header'
complete -c 'debugfs.reiserfs' -s d -d 'prints the formatted nodes of the internal tree of the filesystem'
complete -c 'debugfs.reiserfs' -s D -d 'prints the formatted nodes of all used blocks of the filesystem'
complete -c 'debugfs.reiserfs' -s m -d 'prints the contents of the bitmap (slightly useful)'
complete -c 'debugfs.reiserfs' -s o -d 'prints the objectid map (slightly useful)'
complete -c 'debugfs.reiserfs' -s B -d 'takes the list of bad blocks stored in the internal ReiserFS tree and transla…'
complete -c 'debugfs.reiserfs' -s 1 -d 'prints the specified block of the filesystem'
complete -c 'debugfs.reiserfs' -s s -d '\\" scans the partition and prints a line when any kind of reiserfs '
complete -c 'debugfs.reiserfs' -s p -d 'extracts the filesystem\'s metadata with debugreiserfs -p /dev/xxx | gzip -c >…'
complete -c 'debugfs.reiserfs' -s u -d 'builds the ReiserFS filesystem image with gunzip -c xxx'
complete -c 'debugfs.reiserfs' -s S -d 'When -S is not specified -p  '
complete -c 'debugfs.reiserfs' -s q -d 'When '

