# decode-dimms
# Autogenerated from man page /usr/share/man/man1/decode-dimms.1.gz
complete -c decode-dimms -s f -l format -d 'Print nice html output'
complete -c decode-dimms -s b -l bodyonly -d 'Don\'t print html header (useful for postprocessing the output)'
complete -c decode-dimms -l side-by-side -d 'Display all DIMMs side-by-side if possible'
complete -c decode-dimms -l merge-cells -d 'Merge neighbour cells with identical values (side-by-side output only, defaul…'
complete -c decode-dimms -l no-merge-cells -d 'Don\'t merge neighbour cells with identical values (side-by-side output only)'
complete -c decode-dimms -s c -l checksum -d 'Decode completely even if checksum fails'
complete -c decode-dimms -s x -d 'Read data from hexdump files'
complete -c decode-dimms -s X -d 'Same as -x except treat multibyte hex data as little endian'
complete -c decode-dimms -s h -l help -d 'Display the usage summary'

