# defrag.f2fs
# Autogenerated from man page /usr/share/man/man8/defrag.f2fs.8.gz
complete -c 'defrag.f2fs' -s s -d 'Specify the starting block address'
complete -c 'defrag.f2fs' -s l -d 'Specify the number of blocks to move'
complete -c 'defrag.f2fs' -s t -d 'Specify the destination block address'
complete -c 'defrag.f2fs' -s i -d 'Set the direction to left'
complete -c 'defrag.f2fs' -s d -d 'Specify the level of debugging options'

