# dmscripts
# Autogenerated from man page /usr/share/man/man1/dmscripts.1.gz
complete -c dmscripts -s A -d 'variable[name-displayed-in-dmenu]=what-it-actually-means'
complete -c dmscripts -s a -d 'variable=( [dq]thing1[dq] [dq]thing2[dq] '

