# dnssec-cds
# Autogenerated from man page /usr/share/man/man1/dnssec-cds.1.gz
complete -c dnssec-cds -s a -d 'When converting CDS records to DS records, this option specifies the acceptab…'
complete -c dnssec-cds -s c -d 'This option specifies the DNS class of the zones'
complete -c dnssec-cds -s D -d 'This option generates DS records from CDNSKEY records if both CDS and CDNSKEY…'
complete -c dnssec-cds -s d -d 'This specifies the location of the parent DS records'
complete -c dnssec-cds -s f -d 'This option specifies the file containing the child\\(aqs CDS and/or CDNSKEY r…'
complete -c dnssec-cds -s i -d 'This option updates the dsset- file in place, instead of writing DS records t…'
complete -c dnssec-cds -s s -d 'This option specifies the date and time after which RRSIG records become acce…'
complete -c dnssec-cds -s T -d 'This option specifies a TTL to be used for new DS records'
complete -c dnssec-cds -s u -d 'This option writes an \\%nsupdate script to the standard output, instead of pr…'
complete -c dnssec-cds -s V -d 'This option prints version information'
complete -c dnssec-cds -s v -d 'This option sets the debugging level'

