# dump.erofs
# Autogenerated from man page /usr/share/man/man1/dump.erofs.1.gz
complete -c 'dump.erofs' -l device -d 'Specify an extra device to be used together'
complete -c 'dump.erofs' -l ls -d 'List directory contents.  An inode should be specified together'
complete -c 'dump.erofs' -l nid -d 'Specify an inode NID in order to print its file information'
complete -c 'dump.erofs' -l path -d 'Specify an inode path in order to print its file information'
complete -c 'dump.erofs' -s e -d 'Show the file extent information.  An inode should be specified together'
complete -c 'dump.erofs' -s V -d 'Print the version number and exit'
complete -c 'dump.erofs' -s s -d 'Show superblock information of the an EROFS-formatted image'
complete -c 'dump.erofs' -s S -d 'Show EROFS disk statistics, including file type/size distribution, number of …'

