# dump.f2fs
# Autogenerated from man page /usr/share/man/man8/dump.f2fs.8.gz
complete -c 'dump.f2fs' -s i -d 'Specify an inode number to dump out'
complete -c 'dump.f2fs' -s n -d 'Specify a range presented by nids to dump NAT entries'
complete -c 'dump.f2fs' -s M -d 'Show all the allocated block addresses given inode number'
complete -c 'dump.f2fs' -s s -d 'Specify a range presented by segment numbers to dump SIT entries'
complete -c 'dump.f2fs' -s a -d 'Specify a range presented by segment numbers to dump SSA entries'
complete -c 'dump.f2fs' -s b -d 'Specify a block address to retrieve its metadata information'
complete -c 'dump.f2fs' -s d -d 'Specify the level of debugging options'

