# ebrowse
# Autogenerated from man page /usr/share/man/man1/ebrowse.1.gz
complete -c ebrowse -s a -l append -d 'append output to existing file'
complete -c ebrowse -s f -l files -d 'read input file names from  FILE'
complete -c ebrowse -s I -l search-path -d 'set search path for input files'
complete -c ebrowse -s m -l min-regexp-length -d 'set minimum regexp length to  N'
complete -c ebrowse -s M -l max-regexp-length -d 'set maximum regexp length to  N'
complete -c ebrowse -s n -l no-nested-classes -d 'exclude nested classes'
complete -c ebrowse -s o -l output-file -d 'set output file name to  FILE'
complete -c ebrowse -s p -l position-info -d 'print info about position in file'
complete -c ebrowse -s s -l no-structs-or-unions -d 'don\'t record structs or unions'
complete -c ebrowse -s v -l verbose -d 'be verbose'
complete -c ebrowse -s V -l very-verbose -d 'be very verbose'
complete -c ebrowse -s x -l no-regexps -d 'don\'t record regular expressions'
complete -c ebrowse -l help -d 'display this help'
complete -c ebrowse -l version -d 'display version info SEE ALSO emacs (1), etags (1), and the full documentatio…'

