# eeprog
# Autogenerated from man page /usr/share/man/man8/eeprog.8.gz
complete -c eeprog -s 8 -d 'Use 8bit address mode for 24c0x. 24C16 [default]'
complete -c eeprog -o 16 -d 'Use 16bit address mode for 24c32. 24C256'
complete -c eeprog -s r -d 'Read count (1 if omitted) bytes from addr and print them to the standard outp…'
complete -c eeprog -s w -d 'Write input (stdin) at address addr of the EEPROM'
complete -c eeprog -s h -d 'Print this help'
complete -c eeprog -s x -d 'Set hex output mode'
complete -c eeprog -s d -d 'Dummy mode, display what *would* have been done'
complete -c eeprog -s f -d 'Disable warnings and don\'t ask confirmation'
complete -c eeprog -s q -d 'Quiet mode'

