# emacsclient
# Autogenerated from man page /usr/share/man/man1/emacsclient.1.gz
complete -c emacsclient -s a -l alternate-editor -d 'If the Emacs server is not running, run the specified shell command instead'
complete -c emacsclient -s c -l create-frame -d 'Create a new frame instead of trying to use the current Emacs frame'
complete -c emacsclient -s F -l frame-parameters -d 'Set the parameters of a newly-created frame'
complete -c emacsclient -s d -l display -d 'Tell the server to display the files on the given display'
complete -c emacsclient -s e -l eval -d 'Do not visit files but instead evaluate the arguments as Emacs Lisp expressio…'
complete -c emacsclient -s f -l server-file -d 'Use TCP configuration file FILENAME for communication'
complete -c emacsclient -s n -l no-wait -d 'Return immediately without waiting for you to "finish" the buffer in Emacs'
complete -c emacsclient -o nw -s t -l tty -d 'Open a new Emacs frame on the current terminal'
complete -c emacsclient -s s -l socket-name -d 'Use socket named FILENAME for communication'
complete -c emacsclient -s V -l version -d 'Print version information and exit'
complete -c emacsclient -s H -l help -d 'Print this usage information message and exit'

