# fsck.jfs
# Autogenerated from man page /usr/share/man/man8/fsck.jfs.8.gz
complete -c 'fsck.jfs' -s a -d 'Autocheck mode - Replay the transaction log'
complete -c 'fsck.jfs' -s b -d '\\" *currently unused* Perform Bad Block List utility processing only. \\"'
complete -c 'fsck.jfs' -s c -d '\\" After a replay of the transaction log completes successfully, only continu…'
complete -c 'fsck.jfs' -s f -d 'Replay the transaction log and force checking even if the file system appears…'
complete -c 'fsck.jfs' -s j -d 'Specify the journal device'
complete -c 'fsck.jfs' -s n -d 'Open the file system read only.   Do not replay the transaction log'
complete -c 'fsck.jfs' -l omit_journal_replay -d 'Omit the replay of the transaction log'
complete -c 'fsck.jfs' -s p -d 'Automatically repair ("preen") the file system.   Replay the transaction log'
complete -c 'fsck.jfs' -l replay_journal_only -d 'Only replay the transaction log'
complete -c 'fsck.jfs' -s v -d 'Verbose messaging - print details and debug statements to stdout'
complete -c 'fsck.jfs' -s V -d 'Print version information and exit (regardless of any other chosen options)'

