# fsck.erofs
# Autogenerated from man page /usr/share/man/man1/fsck.erofs.1.gz
complete -c 'fsck.erofs' -s V -d 'Print the version number of fsck. erofs and exit'
complete -c 'fsck.erofs' -s d -d 'Specify the level of debugging messages'
complete -c 'fsck.erofs' -s p -d 'Print total compression ratio of all files including compressed and non-compr…'
complete -c 'fsck.erofs' -l device -d 'Specify an extra device to be used together'
complete -c 'fsck.erofs' -l extract -d 'Check if all files are well encoded'
complete -c 'fsck.erofs' -l help -d 'Display this help and exit.  AUTHOR This version of fsck'

