# fsck.f2fs
# Autogenerated from man page /usr/share/man/man8/fsck.f2fs.8.gz
complete -c 'fsck.f2fs' -s a -d 'Enable to run file system check only if a bug was reported by the F2FS kernel…'
complete -c 'fsck.f2fs' -s f -d 'Enable to fix all the inconsistency in the partition'
complete -c 'fsck.f2fs' -s M -d 'Enable to show all the filenames and inode numbers stored in the image'
complete -c 'fsck.f2fs' -s p -d 'Same as "-a" to support general fsck convention'
complete -c 'fsck.f2fs' -s t -d 'Enable to show every directory entries in the partition'
complete -c 'fsck.f2fs' -s d -d 'Specify the level of debugging options'

