# fsck.exfat
# Autogenerated from man page /usr/share/man/man8/fsck.exfat.8.gz
complete -c 'fsck.exfat' -s a -d 'This  option  does  the same thing as the -p option'
complete -c 'fsck.exfat' -s n -d 'Check the filesystem but do not attempt to repair the filesystem'
complete -c 'fsck.exfat' -s p -d 'Repair the filesystem without user interaction if it can be done safely'
complete -c 'fsck.exfat' -s r -d 'Repair the filesystem interactively'
complete -c 'fsck.exfat' -s v -d 'Prints verbose debugging information while checking the exFAT filesystem'
complete -c 'fsck.exfat' -s V -d 'Prints the version number and exits'
complete -c 'fsck.exfat' -s y -d 'Repair the filesystem answering yes to all questions'

