# git-hook
# Autogenerated from man page /usr/share/man/man1/git-hook.1.gz
complete -c git-hook -l ignore-missing -d 'Ignore any missing hook by quietly returning zero'
complete -c git-hook -l end-of-options -d 'gitcli(7)).  See githooks(5) for arguments hooks might expect (if any)'

