# i2cdetect
# Autogenerated from man page /usr/share/man/man8/i2cdetect.8.gz
complete -c i2cdetect -s y -d 'Disable interactive mode'
complete -c i2cdetect -s a -d 'Force scanning of non-regular addresses.  Not recommended'
complete -c i2cdetect -s q -d 'Use SMBus "quick write" command for probing.  Not recommended'
complete -c i2cdetect -s r -d 'Use SMBus "receive byte" command for probing.  Not recommended'
complete -c i2cdetect -s F -d 'Display the list of functionalities implemented by the adapter and exit'
complete -c i2cdetect -s V -d 'Display the version and exit'
complete -c i2cdetect -s l -d 'Output a list of installed busses'

