# i2cdump
# Autogenerated from man page /usr/share/man/man8/i2cdump.8.gz
complete -c i2cdump -s V -d 'Display the version and exit'
complete -c i2cdump -s f -d 'Force access to the device even if it is already busy'
complete -c i2cdump -s r -d 'Limit the range of registers being accessed'
complete -c i2cdump -s y -d 'Disable interactive mode'
complete -c i2cdump -s a -d 'Allow using addresses between 0x00 - 0x07 and 0x78 - 0x7f.  Not recommended'

