# i2cget
# Autogenerated from man page /usr/share/man/man8/i2cget.8.gz
complete -c i2cget -s V -d 'Display the version and exit'
complete -c i2cget -s f -d 'Force access to the device even if it is already busy'
complete -c i2cget -s y -d 'Disable interactive mode'
complete -c i2cget -s a -d 'Allow using addresses between 0x00 - 0x07 and 0x78 - 0x7f.  Not recommended'

