# i2cset
# Autogenerated from man page /usr/share/man/man8/i2cset.8.gz
complete -c i2cset -s V -d 'Display the version and exit'
complete -c i2cset -s f -d 'Force access to the device even if it is already busy'
complete -c i2cset -s y -d 'Disable interactive mode'
complete -c i2cset -s m -d 'The mask parameter, if specified, describes which bits of value will be actua…'
complete -c i2cset -s r -d 'Read back the value right after writing it, and compare the result with the v…'
complete -c i2cset -s a -d 'Allow using addresses between 0x00 - 0x07 and 0x78 - 0x7f.  Not recommended'

