# i2ctransfer
# Autogenerated from man page /usr/share/man/man8/i2ctransfer.8.gz
complete -c i2ctransfer -s f -d 'Force access to the device even if it is already busy'
complete -c i2ctransfer -s y -d 'Disable interactive mode'
complete -c i2ctransfer -s v -d 'Enable verbose output.  It will print infos about all messages sent, i. e'
complete -c i2ctransfer -s V -d 'Display the version and exit'
complete -c i2ctransfer -s a -d 'Allow using addresses between 0x00 - 0x07 and 0x78 - 0x7f.  Not recommended'

