# iscsiuio
# Autogenerated from man page /usr/share/man/man8/iscsiuio.8.gz
complete -c iscsiuio -s d -l debug -d 'This is to enable debug mode where debug messages will be sent to stdout The …'
complete -c iscsiuio -s f -l foreground -d 'This is to enable foreground mode so that this application doesn\'t get sent i…'
complete -c iscsiuio -s v -l version -d 'This is to print the version'
complete -c iscsiuio -s p -l pid -d 'Use pidfile (default  /run/iscsiuio. pid )'
complete -c iscsiuio -s h -l help -d 'Display this help and exit.  AUTHOR Benjamin Li - benli@broadcom. com'

