# isnsadm
# Autogenerated from man page /usr/share/man/man8/isnsadm.8.gz
complete -c isnsadm -l config -s c -d 'This option overrides the default configuration file'
complete -c isnsadm -l debug -s d -d 'enables debugging.  Valid facilities are . PP . TS tab(,),box,center; lb|lr'
complete -c isnsadm -l local -d 'makes  isnsadm use a Local (aka Unix) socket when talking to the iSNS server'
complete -c isnsadm -l server -s s -d 'specifies the server to use (if not specified in the configuration file)'
complete -c isnsadm -l control -d 'makes  isnsadm assume the identity of a control node'
complete -c isnsadm -l key -d 'This option is recognized in registration mode only, and lets you specify an …'
complete -c isnsadm -l keyfile -d 'When creating a policy for a new iSNS client,   isnsadm is able to generate a…'
complete -c isnsadm -l help -d 'This will print a help message and exit. \\"--------------------------- '
complete -c isnsadm -l edit-policy -d 'it is acceptable to use node-type as shorthand for policy-node-type '
complete -c isnsadm -l register -d 'option, followed by a list of one or more objects to register with the iSNS s…'
complete -c isnsadm -l replace -d 'Normally, registration mode will add new objects to the network entity associ…'
complete -c isnsadm -l query -d 'option.  A query consists of a list of  attr =  value pairs'
complete -c isnsadm -l enroll -d 'option, followed by the (source) name of the client to enroll'

