# isnsdd
# Autogenerated from man page /usr/share/man/man8/isnsdd.8.gz
complete -c isnsdd -l config -s c -d 'This option overrides the default configuration file'
complete -c isnsdd -l foreground -s f -d 'By default,  isnsd will put itself into the background'
complete -c isnsdd -l role -d 'This tells the discovery daemon in which capacity is should register itself w…'
complete -c isnsdd -l debug -s d -d 'enables debugging'

