# isnsd
# Autogenerated from man page /usr/share/man/man8/isnsd.8.gz
complete -c isnsd -l config -s c -d 'This option overrides the default configuration file'
complete -c isnsd -l foreground -s f -d 'By default,  isnsd will put itself into the background'
complete -c isnsd -s 4 -d 'tells  isnsd to create an IPv4 socket only'
complete -c isnsd -s 6 -d 'tells  isnsd explicitly to create an IPv6 socket only'
complete -c isnsd -l debug -s d -d 'enables debugging.  Valid facilities are . PP . TS tab(,),box,center; lb|lr'
complete -c isnsd -l dump-db -d 'This is a helper function that will read the database from the file system, a…'
complete -c isnsd -l init -d 'This option will create the server\'s authentication key, and the required DSA…'

