# isotest
# Autogenerated from man page /usr/share/man/man1/isotest.1.gz
complete -c isotest -s b -l bytes -d 'Send or Receive packet size'
complete -c isotest -s i -l index -d 'Select the specified HCI device index.  hciNUM is also acceptable'
complete -c isotest -s j -l jitter -d 'Socket jitter buffer'
complete -c isotest -s q -l quiet -d 'Disables packet logging'
complete -c isotest -s t -l timeout -d 'Socket send timeout'
complete -c isotest -s C -l continue -d 'Continuously send packets starting over in case of a file'
complete -c isotest -s W -l defer -d 'Enable deferred setup'
complete -c isotest -s M -l mtu -d 'Socket QoS SDU'
complete -c isotest -s S -l sca/adv-interval -d 'Socket QoS CIS SCA/BIS advertising interval'
complete -c isotest -s P -l packing -d 'Socket QoS Packing'
complete -c isotest -s F -l framing -d 'Socket QoS Framing'
complete -c isotest -s I -l interval -d 'Socket QoS Interval'
complete -c isotest -s L -l latency -d 'Socket QoS Latency'
complete -c isotest -s Y -l phy -d 'Socket QoS PHY'
complete -c isotest -s R -l rtn -d 'Socket QoS retransmissions'
complete -c isotest -s B -l preset -d 'Socket QoS preset'
complete -c isotest -s V -l type -d 'Socket destination address type:'
complete -c isotest -s d -l dump -d '(CIS server/BIS broadcaster) and optionally save the contents to FILE'
complete -c isotest -s c -l reconnect -d 'Reconnect (CIS client)'
complete -c isotest -s m -l multiple -d 'Multiple connects (CIS client)'
complete -c isotest -s r -l receive -d 'optionally save the contents to FILE'
complete -c isotest -s s -l send -d 'optionally use contents from FILE'
complete -c isotest -s n -l silent -d 'Connect and be silent (CIS client/BIS broadcaster)'
complete -c isotest -s h -l help
complete -c isotest -s G -l CIG/BIG
complete -c isotest -s T -l CIS/BIS

