# ld.so
# Autogenerated from man page /usr/share/man/man8/ld.so.8.gz
complete -c 'ld.so' -l argv0 -d 'Set  argv[0] to the value  string before running the program'
complete -c 'ld.so' -l audit -d 'Use objects named in  list as auditors'
complete -c 'ld.so' -l inhibit-cache -d 'Do not use R /etc/ld. so. cache '
complete -c 'ld.so' -l library-path -d 'Use  path instead of  LD_LIBRARY_PATH environment variable setting (see below)'
complete -c 'ld.so' -l inhibit-rpath -d 'Ignore RPATH and RUNPATH information in object names in R list '
complete -c 'ld.so' -l list -d 'List all dependencies and how they are resolved'
complete -c 'ld.so' -l list-tunables -d 'Print the names and values of all tunables, along with the minimum and maximu…'
complete -c 'ld.so' -l preload -d 'Preload the objects specified in R list '
complete -c 'ld.so' -o static -d 'option was given to ld (1) during compilation'
complete -c 'ld.so' -s z -d 'linker option, shared objects in the default paths are skipped'
complete -c 'ld.so' -l verify -d 'Verify that program is dynamically linked and this dynamic linker can handle …'

