# list.1ssl
# Autogenerated from man page /usr/share/man/man1/list.1ssl.gz
complete -c 'list.1ssl' -o help -d 'Display a usage message'
complete -c 'list.1ssl' -s 1 -d 'List the commands, digest-commands, or cipher-commands in a single column'
complete -c 'list.1ssl' -o commands -d 'Display a list of standard commands'
complete -c 'list.1ssl' -o digest-commands -d 'Display a list of message digest commands, which are typically used as input …'
complete -c 'list.1ssl' -o digest-algorithms -d 'Display a list of message digest algorithms'
complete -c 'list.1ssl' -o cipher-commands -d 'Display a list of cipher commands, which are typically used as input to the d…'
complete -c 'list.1ssl' -o cipher-algorithms -d 'Display a list of cipher algorithms'
complete -c 'list.1ssl' -o public-key-algorithms -d 'Display a list of public key algorithms, with each algorithm as a block of mu…'
complete -c 'list.1ssl' -o public-key-methods -d 'Display a list of public key method OIDs: this also includes public key metho…'

