# llvm-tli-checker
# Autogenerated from man page /usr/share/man/man1/llvm-tli-checker.1.gz
complete -c llvm-tli-checker -l dump-tli -d 'Print \\(dqavailable\\(dq/\\(dqnot available\\(dq for each library function, acco…'
complete -c llvm-tli-checker -l help -s h -d 'Print a summary of command line options and exit'
complete -c llvm-tli-checker -l libdir -d 'A base directory to prepend to each library file path'
complete -c llvm-tli-checker -l report -d 'The amount of information to report'
complete -c llvm-tli-checker -l separate -d 'Read and report a summary for each library file separately'
complete -c llvm-tli-checker -l triple -d 'The triple to use for initializing TargetLibraryInfo'

