# luac5.1
# Autogenerated from man page /usr/share/man/man1/luac5.1.1.gz
complete -c 'luac5.1' -s l -d 'produce a listing of the compiled bytecode for Lua\'s virtual machine'
complete -c 'luac5.1' -s o -d 'output to R file , instead of the default  luac. out '
complete -c 'luac5.1' -s p -d 'load files but do not generate any output file'
complete -c 'luac5.1' -s s -d 'strip debug information before writing the output file'
complete -c 'luac5.1' -s v -d 'show version information.  FILES'

