# lxsession-logout
# Autogenerated from man page /usr/share/man/man1/lxsession-logout.1.gz
complete -c lxsession-logout -l prompt -d 'Customize the logout message'
complete -c lxsession-logout -l banner -d 'Customize the logout logo'
complete -c lxsession-logout -l side -d 'The position of the logo'

