# lxshortcut
# Autogenerated from man page /usr/share/man/man1/lxshortcut.1.gz
complete -c lxshortcut -s i -l input -d 'use input-file as source for editing, it may be some XDG menu entry if no ful…'
complete -c lxshortcut -s o -l output -d 'write result into output-file SEE ALSO XDG Desktop Entry Specification AUTHOR…'

