# memhog
# Autogenerated from man page /usr/share/man/man8/memhog.8.gz
complete -c memhog -o 'r<num>	Repeat'
complete -c memhog -o 'f<file>	Open'
complete -c memhog -o 'H	Disable'
complete -c memhog -o 'size	Allocation' -d '	suffix (G=gigabyte, M=megabyte, K=kilobyte) Supported numa-policies:'

