# mkfs.nilfs2
# Autogenerated from man page /usr/share/man/man8/mkfs.nilfs2.8.gz
complete -c 'mkfs.nilfs2' -s b -d 'Specify the size of blocks in bytes'
complete -c 'mkfs.nilfs2' -s B -d 'Specify the number of blocks in a segment, where the segment (also called ful…'
complete -c 'mkfs.nilfs2' -s c -d 'Check the device for bad blocks before building the filesystem'
complete -c 'mkfs.nilfs2' -s f -d 'Force overwrite when an existing filesystem is detected on the device'
complete -c 'mkfs.nilfs2' -s h -d 'Display help message and exit'
complete -c 'mkfs.nilfs2' -s K -d 'Keep, do not attempt to discard blocks at mkfs time (discarding blocks initia…'
complete -c 'mkfs.nilfs2' -s L -d 'Set the volume label for the filesystem to R new-volume-label'
complete -c 'mkfs.nilfs2' -s m -d 'Specify the percentage of the segments reserved for garbage collection'
complete -c 'mkfs.nilfs2' -s n -d 'Cause  mkfs'
complete -c 'mkfs.nilfs2' -s O -d 'Create a filesystem with the given features (filesystem options), overriding …'
complete -c 'mkfs.nilfs2' -s q -d 'Quiet execution.   Useful if  mkfs. nilfs2 is run in a script'
complete -c 'mkfs.nilfs2' -s v -d 'Verbose execution'
complete -c 'mkfs.nilfs2' -s V -d 'Print the version number of mkfs. nilfs2 and exit'

