# mkfs.exfat
# Autogenerated from man page /usr/share/man/man8/mkfs.exfat.8.gz
complete -c 'mkfs.exfat' -s b -l boundary-align -d 'Specifies the alignment for the FAT and the start of the cluster heap'
complete -c 'mkfs.exfat' -s c -l cluster-size -d 'Specifies the cluster size of the exFAT file system'
complete -c 'mkfs.exfat' -s f -l full-format -d 'Performs a full format'
complete -c 'mkfs.exfat' -s h -l help -d 'Prints the help and exit'
complete -c 'mkfs.exfat' -s L -l volume-label -d 'Specifies the volume label to be associated with the exFAT filesystem'
complete -c 'mkfs.exfat' -l pack-bitmap -d 'Attempts to relocate the exFAT allocation bitmap so that it ends at the align…'
complete -c 'mkfs.exfat' -s v -l verbose -d 'Prints verbose debugging information while creating the exFAT filesystem'
complete -c 'mkfs.exfat' -s t -d option
complete -c 'mkfs.exfat' -s V -l version -d 'Prints the version number and exits.  SEE ALSO mkfs (8), mount (8),'

