# mkfs.jfs
# Autogenerated from man page /usr/share/man/man8/mkfs.jfs.8.gz
complete -c 'mkfs.jfs' -s b -d '/"Set the block size for a new JFS partition . /". RS . /" . /"Options for '
complete -c 'mkfs.jfs' -s c -d 'Check the device for bad blocks before building the file system'
complete -c 'mkfs.jfs' -s f -d '/"Force - do not ask for confirmation before creating the file system'
complete -c 'mkfs.jfs' -s j -d 'Create the external JFS journal on  journal_device , create the JFS file syst…'
complete -c 'mkfs.jfs' -s J -d 'Create the JFS journal on its own device or attach an external JFS journal to…'
complete -c 'mkfs.jfs' -s L -d 'Set the volume label for the newly formatted device'
complete -c 'mkfs.jfs' -s O -d 'Provide case-insensitive support for compatibility with OS/2'
complete -c 'mkfs.jfs' -s q -d 'Quiet execution - do not ask for confirmation before creating the file system'
complete -c 'mkfs.jfs' -s s -d 'Set the log size (in megabytes) of the inline log'
complete -c 'mkfs.jfs' -s l
complete -c 'mkfs.jfs' -s U -d 'options of jfs_tune (8). )'
complete -c 'mkfs.jfs' -s V -d 'Print version information and exit (regardless of any other chosen options)'

