# mkfs.reiserfs
# Autogenerated from man page /usr/share/man/man8/mkfs.reiserfs.8.gz
complete -c 'mkfs.reiserfs' -s b -l block-size -d 'N is block size in bytes'
complete -c 'mkfs.reiserfs' -s h -l hash -d 'HASH specifies which hash function will sort the names in the directories'
complete -c 'mkfs.reiserfs' -l format -d 'FORMAT specifies the format for the new filsystem.  Choose format 3. 5 or 3'
complete -c 'mkfs.reiserfs' -s u -l uuid -d 'Sets  the  Universally  Unique  IDentifier  of  the  filesystem  to  UUID  (s…'
complete -c 'mkfs.reiserfs' -s l -l label -d 'Sets  the  volume  label  of  the filesystem'
complete -c 'mkfs.reiserfs' -s q -l quiet -d 'Sets mkreiserfs to work quietly without producing messages, progress or quest…'
complete -c 'mkfs.reiserfs' -s j -l journal-device -d 'FILE is the name of the block device on which is to be places the  filesystem…'
complete -c 'mkfs.reiserfs' -s o -l journal-offset -d 'N is the offset where the journal starts when it is to be on a separate device'
complete -c 'mkfs.reiserfs' -s s -l journal-size -d 'N is the size of the journal in blocks'
complete -c 'mkfs.reiserfs' -s t -l transaction-max-size -d 'N is the maximum transaction size parameter for the journal'
complete -c 'mkfs.reiserfs' -s B -l badblocks -d 'File is the file name of the file that contains the list of blocks to be  mar…'
complete -c 'mkfs.reiserfs' -s f -d 'Forces mkreiserfs to continue even when the device is the whole disk,  looks …'
complete -c 'mkfs.reiserfs' -s d -d 'Sets mkreiserfs to print debugging information during mkreiserfs'
complete -c 'mkfs.reiserfs' -s V -d 'Prints the version and then exits'

