# mkfs.xfs
# Autogenerated from man page /usr/share/man/man8/mkfs.xfs.8.gz
complete -c 'mkfs.xfs' -s c -d 'This option specifies the files that mkfs configuration will be obtained from'
complete -c 'mkfs.xfs' -s f -d 'Force overwrite when an existing filesystem is detected on the device'
complete -c 'mkfs.xfs' -s p -d 'If the optional  -p " protofile" argument is given,  mkfs'
complete -c 'mkfs.xfs' -s q -d 'Quiet option.  Normally  mkfs'
complete -c 'mkfs.xfs' -s L -d 'Set the filesystem R label '
complete -c 'mkfs.xfs' -s N -d 'Causes the file system parameters to be printed out without really creating t…'
complete -c 'mkfs.xfs' -s K -d 'Do not attempt to discard blocks at mkfs time'
complete -c 'mkfs.xfs' -s t -d option
complete -c 'mkfs.xfs' -s l -d and
complete -c 'mkfs.xfs' -s s -d 'option or the'
complete -c 'mkfs.xfs' -s b -d 'option may be used to specify the size of the sector or block'
complete -c 'mkfs.xfs' -s m
complete -c 'mkfs.xfs' -s o -d ') is incompatible with reflink-enabled XFS filesystems'
complete -c 'mkfs.xfs' -s d
complete -c 'mkfs.xfs' -s i
complete -c 'mkfs.xfs' -s n
complete -c 'mkfs.xfs' -o bcdpl -d 'A file may be a regular file, a block special file, a character special file,…'
complete -c 'mkfs.xfs' -s r
complete -c 'mkfs.xfs' -s V -d 'Prints the version number and exits'

