# most
# Autogenerated from man page /usr/share/man/man1/most.1.gz
complete -c most -s 1 -d 'VT100 mode.   This is meaningful only on VMS systems'
complete -c most -s b -d 'Binary mode'
complete -c most -s C -d 'Disable color support'
complete -c most -s c -d 'Make searches case-sensitive'
complete -c most -s d -d 'Omit the backslash mark used to denote a wrapped line'
complete -c most -s M -d 'Disable the use of mmap'
complete -c most -s r -d 'Default to using regexp searches'
complete -c most -s s -d 'Squeeze-mode.   Replace multiple blank lines with a single blank line'
complete -c most -s t -d 'Display tabs as ^I'
complete -c most -s u -d 'Disable UTF-8 mode even if the locale dictates it'
complete -c most -s v -d 'Display control characters as in `^A\' for control A'
complete -c most -s w -d 'Wrap lines'
complete -c most -s z -d 'Disable gunzip-on-the-fly'

