# mount.nfs
# Autogenerated from man page /usr/share/man/man8/mount.nfs.8.gz
complete -c 'mount.nfs' -s r -d 'Mount file system readonly'
complete -c 'mount.nfs' -s v -d 'Be verbose'
complete -c 'mount.nfs' -s V -d 'Print version'
complete -c 'mount.nfs' -s w -d 'Mount file system read-write'
complete -c 'mount.nfs' -s f -d 'Fake mount.  Don\'t actually call the mount system call'
complete -c 'mount.nfs' -s n -d 'Do not update   /etc/mtab'
complete -c 'mount.nfs' -s s -d 'Tolerate sloppy mount options rather than fail'
complete -c 'mount.nfs' -s h -d 'Print help message'

