# mount.nilfs2
# Autogenerated from man page /usr/share/man/man8/mount.nilfs2.8.gz
complete -c 'mount.nilfs2' -s V -d 'Output version'
complete -c 'mount.nilfs2' -s f -d 'Fakes mounting the file system, meaning that the actual system call will be s…'
complete -c 'mount.nilfs2' -s i -d 'Don\'t call mount. nilfs2'
complete -c 'mount.nilfs2' -s n -d 'Mount without writing in /etc/mtab'
complete -c 'mount.nilfs2' -s r -d 'Mount the file system read-only.   A synonym is "-o ro"'
complete -c 'mount.nilfs2' -s v -d 'Verbose mode'
complete -c 'mount.nilfs2' -s w -d 'Mount the file system read/write.  This is the default.  A synonym is "-o rw"'
complete -c 'mount.nilfs2' -s o -d 'Options are specified with a -o flag followed by a comma separated string of …'

