# named-checkconf
# Autogenerated from man page /usr/share/man/man1/named-checkconf.1.gz
complete -c named-checkconf -s h -d 'This option prints the usage summary and exits'
complete -c named-checkconf -s j -d 'When loading a zonefile, this option instructs \\%named to read the journal if…'
complete -c named-checkconf -s l -d 'This option lists all the configured zones'
complete -c named-checkconf -s c -d 'This option specifies that only the \\(dqcore\\(dq configuration should be chec…'
complete -c named-checkconf -s i -d 'This option ignores warnings on deprecated options'
complete -c named-checkconf -s p -d 'This option prints out the \\%named'
complete -c named-checkconf -s t -d 'This option instructs \\%named to chroot to directory, so that include directi…'
complete -c named-checkconf -s v -d 'This option prints the version of the named-checkconf program and exits'
complete -c named-checkconf -s x -d 'When printing the configuration files in canonical form, this option obscures…'
complete -c named-checkconf -s z -d 'This option performs a test load of all zones of type primary found in \\%named'

