# numastat
# Autogenerated from man page /usr/share/man/man8/numastat.8.gz
complete -c numastat -s c -d 'Minimize table display width by dynamically shrinking column widths based on …'
complete -c numastat -s m -d 'Show the meminfo-like system-wide memory usage information'
complete -c numastat -s n -d 'Show the original numastat statistics info'
complete -c numastat -s p -d 'Show per-node memory allocation information for the specified PID or pattern'
complete -c numastat -s s -d 'Sort the table data in descending order before displaying it, so the biggest …'
complete -c numastat -s v -d 'Make some reports more verbose'
complete -c numastat -s V -d 'Display numastat version information and exit'

