# nvme-boot-part-log
# Autogenerated from man page /usr/share/man/man1/nvme-boot-part-log.1.gz
complete -c nvme-boot-part-log -s s -l lsp -d 'The log specified field of LID'
complete -c nvme-boot-part-log -s o -l output-file -d 'File name to which raw binary data will be saved to'
complete -c nvme-boot-part-log -l output-format -d 'Set the reporting format to normal, json, or binary'

