# nvme-supported-log-pages
# Autogenerated from man page /usr/share/man/man1/nvme-supported-log-pages.1.gz
complete -c nvme-supported-log-pages -s o -l output-format -d 'This option will set the reporting format to normal, json, or binary'
complete -c nvme-supported-log-pages -s H -l human-readable -d 'This option will parse and format many of the bit fields into a human-readabl…'

