# nvme-ocp-smart-add-log
# Autogenerated from man page /usr/share/man/man1/nvme-ocp-smart-add-log.1.gz
complete -c nvme-ocp-smart-add-log -s o -l output-format -d 'Set the reporting format to normal or json'

