# nvme-fid-support-effects-log
# Autogenerated from man page /usr/share/man/man1/nvme-fid-support-effects-log.1.gz
complete -c nvme-fid-support-effects-log -s o -l output-format -d 'Set the reporting format to normal, json, or binary'
complete -c nvme-fid-support-effects-log -s H -l human-readable -d 'This option will parse and format many of the bit fields into human-readable …'

