# nvme-dim
# Autogenerated from man page /usr/share/man/man1/nvme-dim.1.gz
complete -c nvme-dim -s t -l task -d 'The task to perform: "register" or "deregister"'
complete -c nvme-dim -s n -l nqn -d 'The DIM command will be sent to the Discovery Controller (DC) matching this N…'
complete -c nvme-dim -s d -l device -d 'The DIM command will be sent to the Discovery Controllers (DC) associated wit…'

