# nvme-wdc-get-unsupported-reqs-log
# Autogenerated from man page /usr/share/man/man1/nvme-wdc-get-unsupported-reqs-log.1.gz
complete -c nvme-wdc-get-unsupported-reqs-log -s o -l output-format -d 'Set the reporting format to normal, or json'

