# nvme-list-endgrp
# Autogenerated from man page /usr/share/man/man1/nvme-list-endgrp.1.gz
complete -c nvme-list-endgrp -s i -l endgrp-id -d 'Retrieve the identify endurance group list structure starting for the given e…'
complete -c nvme-list-endgrp -s o -l output-format -d 'Set the reporting format to normal or json'

