# nvme-cmdset-ind-id-ns
# Autogenerated from man page /usr/share/man/man1/nvme-cmdset-ind-id-ns.1.gz
complete -c nvme-cmdset-ind-id-ns -s n -l namespace-id -d 'Retrieve the identify namespace structure for the given nsid'
complete -c nvme-cmdset-ind-id-ns -s b -l raw-binary -d 'Print the raw buffer to stdout.  Structure is not parsed by program'
complete -c nvme-cmdset-ind-id-ns -s H -l human-readable -d 'This option will parse and format many of the bit fields into human-readable …'
complete -c nvme-cmdset-ind-id-ns -s o -l output-format -d 'Set the reporting format to normal, json, or binary'

