# nvme-lockdown
# Autogenerated from man page /usr/share/man/man1/nvme-lockdown.1.gz
complete -c nvme-lockdown -l ofi -s o -d 'Opcode or Feature Identifier(OFI) specifies the command opcode or Set Feature…'
complete -c nvme-lockdown -l ifc -s f -d 'Interface (INF) field identifies the interfaces affected by this command'
complete -c nvme-lockdown -l prhbt -s p -d 'Prohibit(PRHBT) bit specifies whether to prohibit or allow the command opcode…'
complete -c nvme-lockdown -l scp -s s -d 'Scope(SCP) field specifies the contents of the Opcode or Feature Identifier f…'
complete -c nvme-lockdown -l uuid -s U -d 'UUID Index - If this field is set to a non-zerovalue, then the value of this …'

