# oathtool
# Autogenerated from man page /usr/share/man/man1/oathtool.1.gz
complete -c oathtool -s h -l help -d 'Print help and exit'
complete -c oathtool -s V -l version -d 'Print version and exit'
complete -c oathtool -l hotp -d 'use event-based HOTP mode  (default=on)'
complete -c oathtool -l totp -d 'use time-variant TOTP mode (values "SHA1", "SHA256", or "SHA512")  (default=`…'
complete -c oathtool -s b -l base32 -d 'use base32 encoding of KEY instead of hex (default=off)'
complete -c oathtool -s c -l counter -d 'HOTP counter value'
complete -c oathtool -s s -l time-step-size -d '(default=`30s\')'
complete -c oathtool -s S -l start-time -d 'when to start counting time steps for TOTP (default=`1970-01-01 00:00:00 UTC\')'
complete -c oathtool -s N -l now -d 'use this time as current time for TOTP (default=`now\')'
complete -c oathtool -s d -l digits -d 'number of digits in one-time password'
complete -c oathtool -s w -l window -d 'number of additional OTPs to generate or validate against'
complete -c oathtool -s v -l verbose -d 'explain what is being done  (default=off) EXAMPLES To generate a time-based (…'

