# openssl-version.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-version.1ssl.gz
complete -c 'openssl-version.1ssl' -o help -d 'Print out a usage message'
complete -c 'openssl-version.1ssl' -s a -d 'All information, this is the same as setting all the other flags'
complete -c 'openssl-version.1ssl' -s v -d 'The current OpenSSL version'
complete -c 'openssl-version.1ssl' -s b -d 'The date the current version of OpenSSL was built'
complete -c 'openssl-version.1ssl' -s o -d 'Option information: various options set when the library was built'
complete -c 'openssl-version.1ssl' -s f -d 'Compilation flags'
complete -c 'openssl-version.1ssl' -s p -d 'Platform setting'
complete -c 'openssl-version.1ssl' -s d -d '\\s-1OPENSSLDIR\\s0 setting'

