# openssl-nseq.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-nseq.1ssl.gz
complete -c 'openssl-nseq.1ssl' -o help -d 'Print out a usage message'
complete -c 'openssl-nseq.1ssl' -o in -d 'This specifies the input filename to read or standard input if this option is…'
complete -c 'openssl-nseq.1ssl' -o out -d 'Specifies the output filename or standard output by default'

