# pacignore
# Autogenerated from man page /usr/share/man/man8/pacignore.8.gz
complete -c pacignore -s c -d 'Pacman configuration file, default is /etc/pacman. conf'
complete -c pacignore -s h -d 'Show help script'

