# partclone.chkimg
# Autogenerated from man page /usr/share/man/man8/partclone.chkimg.8.gz
complete -c 'partclone.chkimg' -s s -l source -d 'Source FILE'
complete -c 'partclone.chkimg' -s L -l logfile -d 'put special path to record partclone log information'
complete -c 'partclone.chkimg' -s C -l no_check -d 'Don\\*(Aqt check device size and free space'
complete -c 'partclone.chkimg' -s N -l ncurses -d 'Using Ncurses Text User Interface'
complete -c 'partclone.chkimg' -s X -l dialog -d 'Output message as Dialog Format'
complete -c 'partclone.chkimg' -l ignore_crc -d 'Ignore crc check error'
complete -c 'partclone.chkimg' -s F -l force -d 'Force progress'
complete -c 'partclone.chkimg' -s f -l UI-fresh -d 'put special second to different interval'
complete -c 'partclone.chkimg' -o dlevel -l debug -d 'Set the debug level [1|2|3]'
complete -c 'partclone.chkimg' -s h -l help -d 'Show summary of options'
complete -c 'partclone.chkimg' -s v -l version -d 'Show version of program'

