# pattrs
# Autogenerated from man page /usr/share/man/man1/pattrs.1.gz
complete -c pattrs -s c -l client -d '                         attributes are to be printed (function or all)    --…'
complete -c pattrs -s h -l help
complete -c pattrs -l host -d '                         attributes are to be printed (function or all)    --…'
complete -c pattrs -s n -l nspace
complete -c pattrs -s p -l pid
complete -c pattrs -s s -l server -d '                         attributes are to be printed (function or all)    --…'
complete -c pattrs -s t -l tool -d '                         attributes are to be printed (function or all)    --…'
complete -c pattrs -s v -l verbose -d AUTHORS

