# pcmanfm
# Autogenerated from man page /usr/share/man/man1/pcmanfm.1.gz
complete -c pcmanfm -s d -l daemon-mode -d 'run PCManFM as a daemon (ignored if another PCManFM is already running)'
complete -c pcmanfm -s p -l profile -d 'load another configuration profile instead of "default"'
complete -c pcmanfm -l no-desktop -d 'for Nautilus compatibility . PP . SS Per-instance options:'
complete -c pcmanfm -l desktop -d 'launch desktop manager (ignores -d)'
complete -c pcmanfm -l desktop-off -d 'turn off desktop manager if it\'s running'
complete -c pcmanfm -l desktop-pref -d 'open desktop preference dialog'
complete -c pcmanfm -l one-screen -d 'manage desktop only on current X screen (only if --desktop is used)'
complete -c pcmanfm -s n -l new-win -d 'open directories in new window'
complete -c pcmanfm -l role -d 'set X role for window (only if -n is used)'
complete -c pcmanfm -l wallpaper-mode -d 'Set mode of desktop wallpaper, mode is:  color (fill with solid color),  stre…'
complete -c pcmanfm -s w -l set-wallpaper -d 'set desktop wallpaper from image file'
complete -c pcmanfm -l show-pref -d 'open preferences dialog on page n'
complete -c pcmanfm -s f -l find-files -d 'open a file search dialog window'

