# pevent
# Autogenerated from man page /usr/share/man/man1/pevent.1.gz
complete -c pevent -s e -l event
complete -c pevent -s h -l help
complete -c pevent -s p -l pid
complete -c pevent -s r -l range
complete -c pevent -s v -l verbose -d AUTHORS

