# pkeyparam.1ssl
# Autogenerated from man page /usr/share/man/man1/pkeyparam.1ssl.gz
complete -c 'pkeyparam.1ssl' -o help -d 'Print out a usage message'
complete -c 'pkeyparam.1ssl' -o in -d 'This specifies the input filename to read parameters from or standard input i…'
complete -c 'pkeyparam.1ssl' -o out -d 'This specifies the output filename to write parameters to or standard output …'
complete -c 'pkeyparam.1ssl' -o text -d 'Prints out the parameters in plain text in addition to the encoded version'
complete -c 'pkeyparam.1ssl' -o noout -d 'Do not output the encoded version of the parameters'
complete -c 'pkeyparam.1ssl' -o engine -d 'Specifying an engine (by its unique id string) will cause pkeyparam to attemp…'

