# plookup
# Autogenerated from man page /usr/share/man/man1/plookup.1.gz
complete -c plookup -s h -l help
complete -c plookup -s p -l pid
complete -c plookup -s t -l timeout -d '                         available'
complete -c plookup -s v -l verbose
complete -c plookup -s w -l wait -d AUTHORS

