# pps
# Autogenerated from man page /usr/share/man/man1/pps.1.gz
complete -c pps -s h -l help
complete -c pps -s n -l nodes -d '   --nspace              Nspace of job whose status is being requested'
complete -c pps -s p -l pid -d '                         to system server    --parseable           Provide pa…'

