# pquery
# Autogenerated from man page /usr/share/man/man1/pquery.1.gz
complete -c pquery -s h -l help
complete -c pquery -s n -l nspace
complete -c pquery -s p -l pid -d '   --system-server       Specifically connect to the system server    --syste…'
complete -c pquery -s v -l verbose -d AUTHORS

