# pskctool
# Autogenerated from man page /usr/share/man/man1/pskctool.1.gz
complete -c pskctool -s h -l help -d 'Print help and exit'
complete -c pskctool -s V -l version -d 'Print version and exit'
complete -c pskctool -l strict -d 'Fail hard on PSKC parse error  (default=off)'
complete -c pskctool -s d -l debug -d 'Show debug messages on stderr  (default=off)'
complete -c pskctool -s q -l quiet -d 'Quiet operation  (default=off)'
complete -c pskctool -s v -l verbose -d 'Produce more output  (default=off) '
complete -c pskctool -s i -l info -d 'Parse and print human readable summary of PSKC input (default=off) P Mode: va…'
complete -c pskctool -s e -l validate -d 'Validate PSKC input against XML Schema  (default=off) P Mode: sign P Digitall…'
complete -c pskctool -l sign -d 'Sign PSKC input  (default=off)'
complete -c pskctool -l sign-key -d 'Private key to sign with'
complete -c pskctool -l sign-crt -d X
complete -c pskctool -l verify -d 'Verify signed PSKC input  (default=off)'
complete -c pskctool -l verify-crt -d 'Trusted X. 509 certificate for verification EXAMPLES See <https://www. nongnu'

