# qalculate-gtk
# Autogenerated from man page /usr/share/man/man1/qalculate-gtk.1.gz
complete -c qalculate-gtk -s f -l file -d 'execute expressions and commands from a file . PP'
complete -c qalculate-gtk -s n -l new-instance -d 'start a new instance of the application . PP'
complete -c qalculate-gtk -l title -d 'specify the window title . PP'
complete -c qalculate-gtk -s v -l version -d 'show application version and exit'
complete -c qalculate-gtk -l help -d 'SEE ALSO Full documentation at https://qalculate. github'

