# rand.1ssl
# Autogenerated from man page /usr/share/man/man1/rand.1ssl.gz
complete -c 'rand.1ssl' -o help -d 'Print out a usage message'
complete -c 'rand.1ssl' -o out -d 'Write to file instead of standard output'
complete -c 'rand.1ssl' -o rand -d 'A file or files containing random data used to seed the random number generat…'
complete -c 'rand.1ssl' -o writerand -d 'Writes random data to the specified file upon exit'
complete -c 'rand.1ssl' -o base64 -d 'Perform base64 encoding on the output'

