# refind-install
# Autogenerated from man page /usr/share/man/man8/refind-install.8.gz
complete -c refind-install -l notesp -d 'This option, which is valid only under OS X, tells refind-install to install …'
complete -c refind-install -l usedefault -d 'You can install rEFInd to a disk using the default/fallback filename of EFI/B…'
complete -c refind-install -l ownhfs -d 'This option should be used only under OS X'
complete -c refind-install -l root -d 'This option is intended to help install rEFInd from a "live CD" or other emer…'
complete -c refind-install -l nodrivers -d 'Ordinarily refind-install attempts to install the driver required to read /bo…'
complete -c refind-install -l alldrivers -d 'When you specify this option, refind-install copies all the driver files for …'
complete -c refind-install -l shim -l preloader -d 'If you pass this option to refind-install, the script will copy the specified…'
complete -c refind-install -l localkeys -d 'This option tells refind-install to generate a new Machine Owner Key (MOK), s…'
complete -c refind-install -l encryptkeys -d 'Ordinarily, if you use the --localkeys option, refind-install stores the loca…'
complete -c refind-install -l keepname -d 'This option is useful only in conjunction with --shim'

