# rehash.1ssl
# Autogenerated from man page /usr/share/man/man1/rehash.1ssl.gz
complete -c 'rehash.1ssl' -o help -s h -d 'Display a brief usage message'
complete -c 'rehash.1ssl' -o old -d 'Use old-style hashing (\\s-1MD5,\\s0 as opposed to \\s-1SHA-1\\s0) for generating…'
complete -c 'rehash.1ssl' -s n -d 'Do not remove existing links'
complete -c 'rehash.1ssl' -o compat -d 'Generate links for both old-style (\\s-1MD5\\s0) and new-style (\\s-1SHA1\\s0) ha…'

