# resize.f2fs
# Autogenerated from man page /usr/share/man/man8/resize.f2fs.8.gz
complete -c 'resize.f2fs' -s t -d 'Specify the size in sectors'
complete -c 'resize.f2fs' -s d -d 'Specify the level of debugging options'

