# rndc-confgen
# Autogenerated from man page /usr/share/man/man8/rndc-confgen.8.gz
complete -c rndc-confgen -s a -d 'This option sets automatic \\%rndc configuration, which creates a file /etc/rn…'
complete -c rndc-confgen -s A -d 'This option specifies the algorithm to use for the TSIG key'
complete -c rndc-confgen -s b -d 'This option specifies the size of the authentication key in bits'
complete -c rndc-confgen -s c -d 'This option is used with the \\%-a option to specify an alternate location for…'
complete -c rndc-confgen -s h -d 'This option prints a short summary of the options and arguments to rndc-confg…'
complete -c rndc-confgen -s k -d 'This option specifies the key name of the \\%rndc authentication key'
complete -c rndc-confgen -s p -d 'This option specifies the command channel port where \\%named listens for conn…'
complete -c rndc-confgen -s q -d 'This option prevets printing the written path in automatic configuration mode'
complete -c rndc-confgen -s s -d 'This option specifies the IP address where \\%named listens for command-channe…'
complete -c rndc-confgen -s t -d 'This option is used with the \\%-a option to specify a directory where \\%named…'
complete -c rndc-confgen -s u -d 'This option is used with the \\%-a option to set the owner of the generated rn…'

