# rpc.idmapd
# Autogenerated from man page /usr/share/man/man8/rpc.idmapd.8.gz
complete -c 'rpc.idmapd' -s h -d 'Display usage message'
complete -c 'rpc.idmapd' -s v -d 'Increases the verbosity level (can be specified multiple times)'
complete -c 'rpc.idmapd' -s f -d 'Runs rpc. idmapd in the foreground and prints all output to the terminal'
complete -c 'rpc.idmapd' -s p -d 'Specifies the location of the RPC pipefs to be path'
complete -c 'rpc.idmapd' -s c -d 'Use configuration file path.  This option is deprecated'
complete -c 'rpc.idmapd' -s C -d 'Client-only: perform no idmapping for any NFS server, even if one is detected'
complete -c 'rpc.idmapd' -s S -d 'Server-only: perform no idmapping for any NFS client, even if one is detected'

