# sess_id.1ssl
# Autogenerated from man page /usr/share/man/man1/sess_id.1ssl.gz
complete -c 'sess_id.1ssl' -o help -d 'Print out a usage message'
complete -c 'sess_id.1ssl' -o inform -d 'This specifies the input format'
complete -c 'sess_id.1ssl' -o outform -d 'This specifies the output format'
complete -c 'sess_id.1ssl' -o in -d 'This specifies the input filename to read session information from or standar…'
complete -c 'sess_id.1ssl' -o out -d 'This specifies the output filename to write session information to or standar…'
complete -c 'sess_id.1ssl' -o text -d 'Prints out the various public or private key components in plain text in addi…'
complete -c 'sess_id.1ssl' -o cert -d 'If a certificate is present in the session it will be output using this optio…'
complete -c 'sess_id.1ssl' -o noout -d 'This option prevents output of the encoded version of the session'

