# sload.f2fs
# Autogenerated from man page /usr/share/man/man8/sload.f2fs.8.gz
complete -c 'sload.f2fs' -s f -d 'Specify the source directory path to be loaded'
complete -c 'sload.f2fs' -s t -d 'Specify the mount point path in the partition to load'
complete -c 'sload.f2fs' -s d -d 'Specify the level of debugging options'
complete -c 'sload.f2fs' -s P -d 'Preserve owner: user and group'
complete -c 'sload.f2fs' -s c -d 'Enable a cluster-based file compression'
complete -c 'sload.f2fs' -s L -d 'Specify cluster size in power of two blocks'
complete -c 'sload.f2fs' -s a -d 'Choose the algorithm for compression'
complete -c 'sload.f2fs' -s i -d 'Specify a file extension to include for the compression'
complete -c 'sload.f2fs' -s x -d 'Specify a file extension to exclude from compression'
complete -c 'sload.f2fs' -s m -d 'Specify a minimum block count saved (by compression) per cluster'
complete -c 'sload.f2fs' -s r -d 'Specify read-only flag for the compressed files'

