# tsig-keygen
# Autogenerated from man page /usr/share/man/man8/tsig-keygen.8.gz
complete -c tsig-keygen -s a -d 'This option specifies the algorithm to use for the TSIG key'
complete -c tsig-keygen -s h -d 'This option prints a short summary of options and arguments'

