# tune.exfat
# Autogenerated from man page /usr/share/man/man8/tune.exfat.8.gz
complete -c 'tune.exfat' -s l -d 'Print the volume label of the exFAT filesystem'
complete -c 'tune.exfat' -s L -d 'Set the volume label of the filesystem to the provided argument'
complete -c 'tune.exfat' -s i -d 'Print the volume serial of the exFAT filesystem'
complete -c 'tune.exfat' -s I -d 'Set the volume serial of the filesystem to the provided argument'
complete -c 'tune.exfat' -s v -d 'Prints verbose debugging information while extracting or tuning parameters of…'
complete -c 'tune.exfat' -s V -d 'Prints the version number and exits'

