# umount.nfs
# Autogenerated from man page /usr/share/man/man8/umount.nfs.8.gz
complete -c 'umount.nfs' -s f -d 'Force unmount the file system in case of unreachable NFS system'
complete -c 'umount.nfs' -s v -d 'Be verbose'
complete -c 'umount.nfs' -s n -d 'Do not update   /etc/mtab'
complete -c 'umount.nfs' -s r -d 'In case unmounting fails, try to mount read-only'
complete -c 'umount.nfs' -s l -d 'Lazy unmount'
complete -c 'umount.nfs' -s h -d 'Print help message'

