# umount.nilfs2
# Autogenerated from man page /usr/share/man/man8/umount.nilfs2.8.gz
complete -c 'umount.nilfs2' -s V -d 'Print version and exit'
complete -c 'umount.nilfs2' -s i -d 'Don\'t call umount. nilfs2.   Valid for umount(8)'
complete -c 'umount.nilfs2' -s n -d 'Unmount without writing in /etc/mtab'
complete -c 'umount.nilfs2' -s r -d 'In case unmounting fails, try to remount read-only'
complete -c 'umount.nilfs2' -s v -d 'Verbose mode.  THE LOOP DEVICE umount'

