# umount.ecryptfs_private
# Autogenerated from man page /usr/share/man/man1/umount.ecryptfs_private.1.gz
complete -c 'umount.ecryptfs_private' -s f -d 'Force the unmount, ignoring the value of the mount counter in /tmp/ecryptfs-U…'

