#!/usr/bin/bash

link() {
  local src="$DOTFILES/$1" dest="$HOME/$1"
  [ "$(readlink -f "$dest")" = "$(readlink -f "$src")" ] && return 0
  [ -e "$dest" ] || [ -L "$dest" ] && mv -v "$dest" "$dest.bak.$(date +%Y%m%d-%H%M%S)"
  ln -svfT "$src" "$dest"
}

link ".config"
link ".local"
link ".xprofile"
