#!/usr/bin/bash

## Link in `.config` folder
LINKSC=("tmux/.tmux.conf" "vim/.vimrc")

linkc() {
  ln -sf $DOTFILES/.config/$1 $HOME
}

for i in "${LINKSC[@]}"; do
  linkc $i
done

## Link directly the files; not in `.config` but are config files.
LINKSD=(".bashrc" ".vim" ".doom.d")

linkd() {
  ln -sf "$DOTFILES/$1" "$HOME"
}

for i in "${LINKSD[@]}"; do
  linkd "$i"
done

ln -sf $HOME/.config/X11/xinitrc $HOME/.xinitrc
