[mgr]
show_hidden = true

[opener]
edit = [
  { run = 'vim "$@"', block = true },
]
play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" },
]
open = [
  { run = 'xdg-open "$@"', desc = "Open" },
]
read = [
  { run = 'evince "$@"', desc = "Read" },
]

[open]
rules = [
  { mime = "text/*", use = ["edit"] },
  { mime = "video/*", use = ["play"] },

  { mime = "application/json", use = ["edit"] },
  { name = "*.json", use = ["edit"] },
  { name = "*.toml", use = ["edit"] },
  { name = "*.ini", use = ["edit"] },
  { name = "*.conf", use = ["edit"] },
  { name = "*.txt", use = ["edit"] },

  { mime = "application/pdf", use = ["read"] },
  { name = "*.pdf", use = ["read"] },
  { name = "*.djvu", use = ["read"] },
  { name = "*.epub", use = ["read"] },

  # Fallback
  { name = "*", use = ["open"] },
]

