[Buttons]
CheckedSource=-2
CheckedTranslation=-2
Source=@Invalid()
Translation=@Invalid()

[MainWindow]
AutoTranslate=false
CurrentEngine=0
WindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\x14\0\0\t\xff\0\0\x4\x12\0\0\0\0\0\0\0\x14\0\0\t\xff\0\0\x4\x12\0\0\0\0\0\0\0\0\n\0\0\0\0\0\0\0\0\x14\0\0\t\xff\0\0\x4\x12)
