1-click:
  install:
    1-clicks: []
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
    type: ""
access-token: dop_v1_fb0486c8f0ba5b33b643d6a541c75b45959d3621feab00a45f4922e738f3761a
account:
  get:
    format: ""
    no-header: false
  ratelimit:
    format: ""
    no-header: false
action:
  get:
    format: ""
    no-header: false
  list:
    action-type: ""
    after: ""
    before: ""
    format: ""
    no-header: false
    region: ""
    resource-type: ""
    status: ""
  wait:
    format: ""
    no-header: false
    poll-timeout: 5
activations:
  get:
    function: ""
    last: false
    logs: false
    quiet: false
    result: false
    skip: 0
  list:
    count: false
    format: ""
    full: false
    limit: 30
    no-header: false
    since: 0
    skip: 0
    upto: 0
  logs:
    follow: false
    function: ""
    last: false
    limit: 1
    package: ""
    strip: false
  result:
    function: ""
    last: false
    limit: 1
    quiet: false
    skip: 0
alert:
  create:
    compare: ""
    description: ""
    emails: []
    enabled: true
    entities: []
    slack-channels: []
    slack-urls: []
    tags: []
    type: ""
    value: 0
    window: 5m
  delete:
    force: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
  update:
    compare: ""
    description: ""
    emails: []
    enabled: true
    entities: []
    slack-channels: []
    slack-urls: []
    tags: []
    type: ""
    value: 0
    window: 5m
api-url: ""
apps:
  create:
    format: ""
    no-header: false
    project-id: ""
    spec: ""
    upsert: false
    wait: false
  create-deployment:
    force-rebuild: false
    format: ""
    no-header: false
    wait: false
  delete:
    force: false
  get:
    format: ""
    no-header: false
  get-deployment:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
    with-projects: false
  list-alerts:
    format: ""
    no-header: false
  list-buildpacks:
    format: ""
    no-header: false
  list-deployments:
    format: ""
    no-header: false
  list-regions:
    format: ""
    no-header: false
  logs:
    deployment: ""
    follow: false
    tail: -1
    type: run
  propose:
    app: ""
    format: ""
    no-header: false
    spec: ""
  update:
    format: ""
    no-header: false
    spec: ""
    wait: false
  update-alert-destinations:
    app-alert-destinations: ""
    format: ""
    no-header: false
  upgrade-buildpack:
    buildpack: ""
    format: ""
    major-version: 0
    no-header: false
    trigger-deployment: true
auth:
  init:
    token-validation-server: https://cloud.digitalocean.com
  list:
    format: ""
balance:
  get:
    format: ""
    no-header: false
billing-history:
  list:
    format: ""
    no-header: false
cdn:
  create:
    certificate-id: ""
    domain: ""
    format: ""
    no-header: false
    ttl: 3600
  delete:
    force: false
  flush:
    files:
    - '*'
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
  update:
    certificate-id: ""
    domain: ""
    format: ""
    no-header: false
    ttl: 3600
certificate:
  create:
    certificate-chain-path: ""
    dns-names: []
    leaf-certificate-path: ""
    name: ""
    private-key-path: ""
    type: ""
  delete:
    force: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
cluster:
  create:
    1-clicks: []
    auto-upgrade: false
    count: 3
    ha: false
    maintenance-window: any=00:00
    node-pool: []
    region: nyc1
    set-current-context: true
    size: s-1vcpu-2gb
    surge-upgrade: true
    tag: []
    update-kubeconfig: true
    version: latest
    vpc-uuid: ""
    wait: true
  delete:
    dangerous: false
    force: false
    update-kubeconfig: true
  delete-selective:
    force: false
    load-balancers: []
    snapshots: []
    update-kubeconfig: true
    volumes: []
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
  list-associated-resources:
    format: ""
    no-header: false
  update:
    auto-upgrade: false
    cluster-name: ""
    ha: false
    maintenance-window: any=00:00
    set-current-context: true
    surge-upgrade: false
    tag: []
    update-kubeconfig: true
  upgrade:
    version: latest
compute:
  ssh:
    ssh-agent-forwarding: false
    ssh-command: ""
    ssh-key-path: /home/buddhilw/.ssh/id_rsa
    ssh-port: 22
    ssh-private-ip: false
    ssh-user: root
config: /home/buddhilw/.config/doctl/config.yaml
context: default
databases:
  backups:
    format: ""
    no-header: false
  connection:
    format: ""
    no-header: false
  create:
    engine: pg
    num-nodes: 1
    private-network-uuid: ""
    region: nyc1
    restore-from-cluster-name: ""
    restore-from-timestamp: ""
    size: db-s-1vcpu-1gb
    version: ""
    wait: false
  delete:
    force: false
  fork:
    restore-from-cluster-id: ""
    restore-from-timestamp: ""
    wait: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
  migrate:
    private-network-uuid: ""
    region: ""
  resize:
    num-nodes: 0
    size: ""
db:
  delete:
    force: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
dev:
  build:
    app: ""
    build-command: ""
    env-file: ""
    no-cache: false
    registry: ""
    spec: ""
    timeout: 0s
  config:
    set:
      dev-config: ""
    unset:
      dev-config: ""
domain:
  create:
    format: ""
    ip-address: ""
    no-header: false
  delete:
    force: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
droplet:
  actions:
    format: ""
    no-header: false
  backups:
    format: ""
    no-header: false
  create:
    droplet-agent: false
    enable-backups: false
    enable-ipv6: false
    enable-monitoring: false
    enable-private-networking: false
    format: ""
    image: ""
    no-header: false
    region: ""
    size: ""
    ssh-keys: []
    tag-name: ""
    tag-names: []
    user-data: ""
    user-data-file: ""
    volumes: []
    vpc-uuid: ""
    wait: false
  delete:
    force: false
    tag-name: ""
  get:
    format: ""
    no-header: false
    template: ""
  kernels:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
    region: ""
    tag-name: ""
  neighbors:
    format: ""
    no-header: false
  snapshots:
    format: ""
    no-header: false
  tag:
    tag-name: ""
  untag:
    tag-name: []
droplet-action:
  change-kernel:
    format: ""
    kernel-id: 0
    no-header: false
    wait: false
  disable-backups:
    format: ""
    no-header: false
    wait: false
  enable-backups:
    format: ""
    no-header: false
    wait: false
  enable-ipv6:
    format: ""
    no-header: false
    wait: false
  enable-private-networking:
    format: ""
    no-header: false
    wait: false
  get:
    action-id: 0
    format: ""
    no-header: false
  password-reset:
    format: ""
    no-header: false
    wait: false
  power-cycle:
    format: ""
    no-header: false
    wait: false
  power-off:
    format: ""
    no-header: false
    wait: false
  power-on:
    format: ""
    no-header: false
    wait: false
  reboot:
    format: ""
    no-header: false
    wait: false
  rebuild:
    format: ""
    image: ""
    no-header: false
    wait: false
  rename:
    droplet-name: ""
    format: ""
    no-header: false
    wait: false
  resize:
    format: ""
    no-header: false
    resize-disk: false
    size: ""
    wait: false
  restore:
    format: ""
    image-id: 0
    no-header: false
    wait: false
  shutdown:
    format: ""
    no-header: false
    wait: false
  snapshot:
    format: ""
    no-header: false
    snapshot-name: ""
    wait: false
firewall:
  add-droplets:
    droplet-ids: []
  add-rules:
    inbound-rules: ""
    outbound-rules: ""
  add-tags:
    tag-names: []
  create:
    droplet-ids: []
    format: ""
    inbound-rules: ""
    name: ""
    no-header: false
    outbound-rules: ""
    tag-names: []
  delete:
    force: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
  list-by-droplet:
    format: ""
    no-header: false
  remove-droplets:
    droplet-ids: []
  remove-rules:
    inbound-rules: ""
    outbound-rules: ""
  remove-tags:
    tag-names: []
  update:
    droplet-ids: []
    format: ""
    inbound-rules: ""
    name: ""
    no-header: false
    outbound-rules: ""
    tag-names: []
firewalls:
  append:
    rule: ""
  remove:
    uuid: ""
  replace:
    rule: []
functions:
  get:
    code: false
    save: false
    save-as: ""
    save-env: ""
    save-env-json: ""
    url: false
  invoke:
    full: false
    no-wait: false
    param: []
    param-file: ""
    web: false
  list:
    count: false
    format: ""
    limit: ""
    name: false
    name-sort: false
    no-header: false
    skip: ""
garbage-collection:
  get-active:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
  start:
    exclude-unreferenced-blobs: false
    force: false
    format: ""
    include-untagged-manifests: false
    no-header: false
image:
  create:
    image-description: ""
    image-distribution: Unknown
    image-url: ""
    region: ""
    tag-names: []
  delete:
    force: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
    public: false
  list-application:
    format: ""
    no-header: false
    public: true
  list-distribution:
    format: ""
    no-header: false
    public: true
  list-user:
    format: ""
    no-header: false
    public: false
  update:
    format: ""
    image-name: ""
    no-header: false
image-action:
  get:
    action-id: 0
    format: ""
    no-header: false
  transfer:
    format: ""
    no-header: false
    region: ""
    wait: false
invoice:
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
  summary:
    format: ""
    no-header: false
kubeconfig:
  exec-credential:
    version: ""
  save:
    alias: ""
    expiry-seconds: 0
    set-current-context: true
  show:
    expiry-seconds: 0
load-balancer:
  add-droplets:
    droplet-ids: []
  add-forwarding-rules:
    forwarding-rules: ""
  create:
    algorithm: round_robin
    allow-list: []
    deny-list: []
    disable-lets-encrypt-dns-records: false
    droplet-ids: []
    enable-backend-keepalive: false
    enable-proxy-protocol: false
    forwarding-rules: ""
    health-check: ""
    http-idle-timeout-seconds: 0
    name: ""
    project-id: ""
    redirect-http-to-https: false
    region: ""
    size: ""
    size-unit: 0
    sticky-sessions: ""
    tag-name: ""
    vpc-uuid: ""
    wait: false
  delete:
    force: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
  remove-droplets:
    droplet-ids: []
  remove-forwarding-rules:
    forwarding-rules: ""
  update:
    algorithm: round_robin
    allow-list: []
    deny-list: []
    disable-lets-encrypt-dns-records: false
    droplet-ids: []
    enable-backend-keepalive: false
    enable-proxy-protocol: false
    forwarding-rules: ""
    health-check: ""
    name: ""
    project-id: ""
    redirect-http-to-https: false
    region: ""
    size: ""
    size-unit: 0
    sticky-sessions: ""
    tag-name: ""
    vpc-uuid: ""
maintenance-window:
  get:
    format: ""
    no-header: false
  update:
    day: ""
    hour: ""
namespaces:
  create:
    label: ""
    no-connect: false
    region: ""
  delete:
    force: false
  list:
    format: ""
    no-header: false
node-pool:
  create:
    auto-scale: false
    count: 0
    label: []
    max-nodes: 0
    min-nodes: 0
    name: ""
    size: ""
    tag: []
    taint: []
  delete:
    force: false
  delete-node:
    force: false
    skip-drain: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
  recycle:
    node-ids: ""
  replace-node:
    force: false
    skip-drain: false
  update:
    auto-scale: false
    count: 0
    label: []
    max-nodes: 0
    min-nodes: 0
    name: ""
    tag: []
    taint: []
options:
  regions:
    engine: ""
  slugs:
    engine: ""
  versions:
    engine: ""
output: text
pool:
  create:
    db: ""
    mode: transaction
    size: 0
    user: ""
  delete:
    force: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
projects:
  create:
    description: ""
    environment: ""
    format: ""
    name: ""
    no-header: false
    purpose: ""
  delete:
    force: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
  update:
    description: ""
    environment: ""
    format: ""
    is_default: false
    name: ""
    no-header: false
    purpose: ""
records:
  create:
    format: ""
    no-header: false
    record-data: ""
    record-flags: 0
    record-name: ""
    record-port: 0
    record-priority: 0
    record-tag: ""
    record-ttl: 1800
    record-type: ""
    record-weight: 0
  delete:
    force: false
  list:
    format: ""
    no-header: false
  update:
    format: ""
    no-header: false
    record-data: ""
    record-flags: 0
    record-id: 0
    record-name: ""
    record-port: 0
    record-priority: 0
    record-tag: ""
    record-ttl: 0
    record-type: ""
    record-weight: 0
region:
  list:
    format: ""
    no-header: false
registry:
  create:
    region: ""
    subscription-tier: basic
  delete:
    force: false
  docker-config:
    expiry-seconds: 0
    read-write: false
  get:
    format: ""
    no-header: false
  kubernetes-manifest:
    name: ""
    namespace: kube-system
  login:
    expiry-seconds: 0
    read-only: false
  logout:
    authorization-server-endpoint: https://cloud.digitalocean.com/v1/oauth/revoke
replica:
  create:
    private-network-uuid: ""
    region: nyc1
    size: db-s-1vcpu-1gb
  delete:
    force: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
repository:
  delete-manifest:
    force: false
  delete-tag:
    force: false
  list:
    format: ""
    no-header: false
  list-manifests:
    format: ""
    no-header: false
  list-tags:
    format: ""
    no-header: false
  list-v2:
    format: ""
    no-header: false
required:
  apps:
    create:
      spec: true
    propose:
      spec: true
    update:
      spec: true
    upgrade-buildpack:
      buildpack: true
  certificate:
    create:
      name: true
  cluster:
    create:
      region: true
  databases:
    fork:
      restore-from-cluster-id: true
    migrate:
      region: true
    resize:
      num-nodes: true
      size: true
  droplet:
    create:
      image: true
      size: true
    tag:
      tag-name: true
  droplet-action:
    change-kernel:
      kernel-id: true
    get:
      action-id: true
    rebuild:
      image: true
    rename:
      droplet-name: true
    resize:
      size: true
    restore:
      image-id: true
    snapshot:
      snapshot-name: true
  firewall:
    create:
      name: true
    update:
      name: true
  firewalls:
    append:
      rule: true
    remove:
      uuid: true
    replace:
      rule: true
  image:
    create:
      image-url: true
      region: true
    update:
      image-name: true
  image-action:
    get:
      action-id: true
    transfer:
      region: true
  load-balancer:
    create:
      name: true
      region: true
  maintenance-window:
    update:
      day: true
      hour: true
  namespaces:
    create:
      label: true
      region: true
  node-pool:
    create:
      count: true
      name: true
      size: true
  options:
    slugs:
      engine: true
  pool:
    create:
      db: true
      size: true
  projects:
    create:
      name: true
      purpose: true
  registry:
    create:
      subscription-tier: true
  ssh-key:
    create:
      public-key: true
    import:
      public-key-file: true
    update:
      key-name: true
  tag:
    apply:
      resource: true
    remove:
      resource: true
  volume:
    create:
      size: true
    snapshot:
      snapshot-name: true
  volume-action:
    get:
      action-id: true
    resize:
      region: true
      size: true
  vpcs:
    create:
      name: true
      region: true
reserved-ip:
  create:
    droplet-id: 0
    format: ""
    no-header: false
    project-id: ""
    region: ""
  delete:
    force: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
    region: ""
reserved-ip-action:
  assign:
    format: ""
    no-header: false
  get:
    format: ""
    no-header: false
  unassign:
    format: ""
    no-header: false
resources:
  assign:
    resource: []
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
serverless:
  connect:
    apihost: ""
    auth: ""
  deploy:
    apihost: ""
    auth: ""
    build-env: ""
    env: ""
    exclude: ""
    include: ""
    incremental: false
    insecure: false
    no-triggers: false
    remote-build: false
    verbose-build: false
    verbose-zip: false
    yarn: false
  get-metadata:
    env: ""
    exclude: ""
    include: ""
    no-triggers: false
  init:
    language: javascript
    overwrite: false
  status:
    credentials: false
    languages: false
    version: false
  undeploy:
    all: false
    apihost: ""
    auth: ""
    force: false
    packages: false
    triggers: false
  watch:
    apihost: ""
    auth: ""
    build-env: ""
    env: ""
    exclude: ""
    include: ""
    insecure: false
    remote-build: false
    verbose-build: false
    verbose-zip: false
    yarn: false
size:
  list:
    format: ""
    no-header: false
snapshot:
  delete:
    force: false
    format: ""
    no-header: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
    region: ""
    resource: ""
spec:
  get:
    deployment: ""
    format: yaml
  validate:
    schema-only: false
sql-mode:
  get:
    format: ""
    no-header: false
ssh-key:
  create:
    format: ""
    no-header: false
    public-key: ""
  delete:
    force: false
  get:
    format: ""
    no-header: false
  import:
    format: ""
    no-header: false
    public-key-file: ""
  list:
    format: ""
    no-header: false
  update:
    format: ""
    key-name: ""
    no-header: false
tag:
  apply:
    resource: []
  delete:
    force: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
  remove:
    resource: []
triggers:
  disable:
    format: ""
    no-header: false
  enable:
    format: ""
    no-header: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    function: ""
    no-header: false
user:
  create:
    mysql-auth-plugin: ""
  delete:
    force: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
volume:
  create:
    desc: ""
    format: ""
    fs-label: ""
    fs-type: ""
    no-header: false
    region: ""
    size: 4TiB
    snapshot: ""
    tag: []
  delete:
    force: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
    region: ""
  snapshot:
    format: ""
    no-header: false
    snapshot-desc: ""
    snapshot-name: ""
    tag: []
volume-action:
  attach:
    wait: false
  detach:
    wait: false
  get:
    action-id: 0
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
  resize:
    region: ""
    size: 0
    wait: false
vpcs:
  create:
    description: ""
    ip-range: ""
    name: ""
    region: ""
  delete:
    force: false
  get:
    format: ""
    no-header: false
  list:
    format: ""
    no-header: false
  update:
    default: false
    description: ""
    name: ""
