[General]
account_name=ramanujan
allowRemoteNodeMining=false
allow_background_mining=false
allow_p2pool_mining=false
askDesktopShortcut=false
askPasswordBeforeSending=false
askStopLocalNode=false
autosave=true
autosaveMinutes=5
blackTheme=false
blockchainDataDir=/home/ramanujan/block
bootstrapNodeAddress=
chainDropdownSelected=0
checkForUpdates=false
customDecorations=true
daemonFlags=
daemonPassword=
daemonUsername=
displayWalletNameInTitleBar=true
fiatPriceCurrency=xmrusd
fiatPriceEnabled=true
fiatPriceProvider=kraken
fiatPriceToggle=false
hideBalance=false
historyHumanDates=true
historyShowAdvanced=false
is_recovering=false
is_recovering_from_device=false
is_trusted_daemon=false
kdfRounds=1
keyReuseMitigation2=true
language=English (US)
language_wallet=English
locale=en_US
lockOnUserInActivity=true
lockOnUserInActivityInterval=5
logCategories=
logLevel=0
miningIgnoreBattery=true
miningModeSelected=0
nettype=0
p2poolFlags=
proxyAddress=127.0.0.1:9050
proxyEnabled=true
pruneBlockchain=true
receiveShowAdvanced=false
remoteNodeAddress=
remoteNodesSerialized="{\"selected\":0,\"nodes\":[]}"
restore_height=3460966
segregatePreForkOutputs=true
segregationHeight=0
transferShowAdvanced=false
useRemoteNode=false
walletMode=2
wallet_path=/home/ramanujan/Monero/wallets/ramanujan/ramanujan

[QQControlsFileDialog]
favoriteFolders=@Invalid()
height=0
sidebarSplit=104.62500000000001
sidebarVisible=false
sidebarWidth=80
width=0
